// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: gnss_psr_dopp_residual
 *
 * Args:
 *     Pi: Matrix31
 *     Vi: Matrix31
 *     Pj: Matrix31
 *     Vj: Matrix31
 *     rcv_dt: Scalar
 *     rcv_ddt: Scalar
 *     yaw_diff: Scalar
 *     ref_ecef: Matrix31
 *     ion_delay: Scalar
 *     tro_delay: Scalar
 *     ratio: Scalar
 *     tgd: Scalar
 *     sv_pos: Matrix31
 *     sv_vel: Matrix31
 *     svdt: Scalar
 *     svddt: Scalar
 *     freq: Scalar
 *     psr_measured: Scalar
 *     dopp_measured: Scalar
 *     pr_uura: Scalar
 *     dp_uura: Scalar
 *     pr_weight: Scalar
 *     dp_weight: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix21
 *     jacobian: (2x18) jacobian of res wrt args Pi (3), Vi (3), Pj (3), Vj (3), rcv_dt (1), rcv_ddt
 *               (1), yaw_diff (1), ref_ecef (3)
 *     hessian: (18x18) Gauss-Newton hessian for args Pi (3), Vi (3), Pj (3), Vj (3), rcv_dt (1),
 *              rcv_ddt (1), yaw_diff (1), ref_ecef (3)
 *     rhs: (18x1) Gauss-Newton rhs for args Pi (3), Vi (3), Pj (3), Vj (3), rcv_dt (1), rcv_ddt
 *          (1), yaw_diff (1), ref_ecef (3)
 */
template <typename Scalar>
void GnssPsrDoppFactor(const Eigen::Matrix<Scalar, 3, 1>& Pi, const Eigen::Matrix<Scalar, 3, 1>& Vi,
                       const Eigen::Matrix<Scalar, 3, 1>& Pj, const Eigen::Matrix<Scalar, 3, 1>& Vj,
                       const Scalar rcv_dt, const Scalar rcv_ddt, const Scalar yaw_diff,
                       const Eigen::Matrix<Scalar, 3, 1>& ref_ecef, const Scalar ion_delay,
                       const Scalar tro_delay, const Scalar ratio, const Scalar tgd,
                       const Eigen::Matrix<Scalar, 3, 1>& sv_pos,
                       const Eigen::Matrix<Scalar, 3, 1>& sv_vel, const Scalar svdt,
                       const Scalar svddt, const Scalar freq, const Scalar psr_measured,
                       const Scalar dopp_measured, const Scalar pr_uura, const Scalar dp_uura,
                       const Scalar pr_weight, const Scalar dp_weight, const Scalar epsilon,
                       Eigen::Matrix<Scalar, 2, 1>* const res = nullptr,
                       Eigen::Matrix<Scalar, 2, 18>* const jacobian = nullptr,
                       Eigen::Matrix<Scalar, 18, 18>* const hessian = nullptr,
                       Eigen::Matrix<Scalar, 18, 1>* const rhs = nullptr) {
  // Total ops: 1294

  // Unused inputs
  (void)pr_uura;
  (void)dp_uura;

  // Input arrays

  // Intermediate terms (322)
  const Scalar _tmp0 = Scalar(1.0) - ratio;
  const Scalar _tmp1 = Pi(2, 0) * ratio + Pj(2, 0) * _tmp0;
  const Scalar _tmp2 =
      epsilon * ((((ref_ecef(0, 0)) > 0) - ((ref_ecef(0, 0)) < 0)) + Scalar(0.5)) + ref_ecef(0, 0);
  const Scalar _tmp3 = Scalar(1.0) * std::atan2(ref_ecef(1, 0), _tmp2);
  const Scalar _tmp4 = std::cos(_tmp3);
  const Scalar _tmp5 = [&]() {
    const Scalar base = ref_ecef(2, 0);
    return base * base * base;
  }();
  const Scalar _tmp6 = std::pow(ref_ecef(2, 0), Scalar(2));
  const Scalar _tmp7 = std::pow(ref_ecef(1, 0), Scalar(2));
  const Scalar _tmp8 = _tmp7 + epsilon + std::pow(ref_ecef(0, 0), Scalar(2));
  const Scalar _tmp9 =
      40680631590769 * _tmp6 + Scalar(40408299984661.5) * _tmp8 + std::pow(epsilon, Scalar(2));
  const Scalar _tmp10 = std::pow(_tmp9, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp11 = Scalar(1.0) / (epsilon + Scalar(40408299984661.5));
  const Scalar _tmp12 = _tmp10 * _tmp11;
  const Scalar _tmp13 = Scalar(4.4917426690159599e+38) * _tmp12 * _tmp5 + ref_ecef(2, 0);
  const Scalar _tmp14 = (_tmp8 * std::sqrt(_tmp8));
  const Scalar _tmp15 = std::sqrt(_tmp8);
  const Scalar _tmp16 = -Scalar(1.09675613733197e+25) * _tmp10 * _tmp14 + _tmp15 + epsilon;
  const Scalar _tmp17 = Scalar(1.0) / (_tmp16);
  const Scalar _tmp18 = Scalar(1.0) * std::atan(_tmp13 * _tmp17);
  const Scalar _tmp19 = _tmp18;
  const Scalar _tmp20 = std::cos(_tmp19);
  const Scalar _tmp21 = _tmp20 * _tmp4;
  const Scalar _tmp22 = Pi(0, 0) * ratio + Pj(0, 0) * _tmp0;
  const Scalar _tmp23 = std::sin(_tmp19);
  const Scalar _tmp24 = std::sin(yaw_diff);
  const Scalar _tmp25 = _tmp24 * _tmp4;
  const Scalar _tmp26 = std::sin(_tmp3);
  const Scalar _tmp27 = std::cos(yaw_diff);
  const Scalar _tmp28 = _tmp26 * _tmp27;
  const Scalar _tmp29 = -_tmp23 * _tmp25 - _tmp28;
  const Scalar _tmp30 = Pi(1, 0) * ratio + Pj(1, 0) * _tmp0;
  const Scalar _tmp31 = _tmp27 * _tmp4;
  const Scalar _tmp32 = _tmp24 * _tmp26;
  const Scalar _tmp33 = -_tmp23 * _tmp31 + _tmp32;
  const Scalar _tmp34 = _tmp1 * _tmp21 + _tmp22 * _tmp29 + _tmp30 * _tmp33 + ref_ecef(0, 0);
  const Scalar _tmp35 = _tmp20 * _tmp26;
  const Scalar _tmp36 = -_tmp23 * _tmp32 + _tmp31;
  const Scalar _tmp37 = -_tmp23 * _tmp28 - _tmp25;
  const Scalar _tmp38 = _tmp1 * _tmp35 + _tmp22 * _tmp36 + _tmp30 * _tmp37 + ref_ecef(1, 0);
  const Scalar _tmp39 = -_tmp34 + sv_pos(0, 0);
  const Scalar _tmp40 = -_tmp38 + sv_pos(1, 0);
  const Scalar _tmp41 = _tmp20 * _tmp27;
  const Scalar _tmp42 = _tmp20 * _tmp24;
  const Scalar _tmp43 =
      -_tmp1 * _tmp23 - _tmp22 * _tmp42 - _tmp30 * _tmp41 - ref_ecef(2, 0) + sv_pos(2, 0);
  const Scalar _tmp44 = std::sqrt(Scalar(std::pow(_tmp39, Scalar(2)) + std::pow(_tmp40, Scalar(2)) +
                                         std::pow(_tmp43, Scalar(2)) + epsilon));
  const Scalar _tmp45 = -Scalar(2.4323877909897198e-13) * _tmp34 * sv_pos(1, 0) +
                        Scalar(2.4323877909897198e-13) * _tmp38 * sv_pos(0, 0) + _tmp44 +
                        ion_delay - psr_measured + rcv_dt - Scalar(299792458.0) * svdt +
                        Scalar(299792458.0) * tgd + tro_delay;
  const Scalar _tmp46 = Vi(2, 0) * ratio + Vj(2, 0) * _tmp0;
  const Scalar _tmp47 = Vi(0, 0) * ratio + Vj(0, 0) * _tmp0;
  const Scalar _tmp48 = Vi(1, 0) * ratio + Vj(1, 0) * _tmp0;
  const Scalar _tmp49 = _tmp21 * _tmp46 + _tmp29 * _tmp47 + _tmp33 * _tmp48;
  const Scalar _tmp50 = _tmp35 * _tmp46 + _tmp36 * _tmp47 + _tmp37 * _tmp48;
  const Scalar _tmp51 = Scalar(1.0) / (_tmp44);
  const Scalar _tmp52 =
      -Scalar(2.4323877909897299e-13) * _tmp34 * sv_vel(1, 0) +
      Scalar(2.4323877909897299e-13) * _tmp38 * sv_vel(0, 0) +
      _tmp39 * _tmp51 * (-_tmp49 + sv_vel(0, 0)) + _tmp40 * _tmp51 * (-_tmp50 + sv_vel(1, 0)) +
      _tmp43 * _tmp51 * (-_tmp23 * _tmp46 - _tmp41 * _tmp48 - _tmp42 * _tmp47 + sv_vel(2, 0)) -
      Scalar(2.4323877909897299e-13) * _tmp49 * sv_pos(1, 0) +
      Scalar(2.4323877909897299e-13) * _tmp50 * sv_pos(0, 0) +
      Scalar(299792458.0) * dopp_measured / freq + rcv_ddt - Scalar(299792458.0) * svddt;
  const Scalar _tmp53 = Scalar(2.4323877909897198e-13) * sv_pos(0, 0);
  const Scalar _tmp54 = std::sin(_tmp18);
  const Scalar _tmp55 = _tmp3;
  const Scalar _tmp56 = std::sin(_tmp55);
  const Scalar _tmp57 = _tmp24 * _tmp56;
  const Scalar _tmp58 = _tmp54 * _tmp57;
  const Scalar _tmp59 = std::cos(_tmp55);
  const Scalar _tmp60 = _tmp27 * _tmp59;
  const Scalar _tmp61 = -_tmp58 + _tmp60;
  const Scalar _tmp62 = _tmp61 * ratio;
  const Scalar _tmp63 = Scalar(2.4323877909897198e-13) * sv_pos(1, 0);
  const Scalar _tmp64 = _tmp24 * _tmp59;
  const Scalar _tmp65 = _tmp54 * _tmp64;
  const Scalar _tmp66 = _tmp27 * _tmp56;
  const Scalar _tmp67 = -_tmp65 - _tmp66;
  const Scalar _tmp68 = _tmp67 * ratio;
  const Scalar _tmp69 = std::cos(_tmp18);
  const Scalar _tmp70 = _tmp24 * _tmp69;
  const Scalar _tmp71 = _tmp1 * _tmp54;
  const Scalar _tmp72 = _tmp27 * _tmp69;
  const Scalar _tmp73 = -_tmp22 * _tmp70 - _tmp30 * _tmp72 - _tmp71 - ref_ecef(2, 0) + sv_pos(2, 0);
  const Scalar _tmp74 = 2 * _tmp73;
  const Scalar _tmp75 = _tmp74 * ratio;
  const Scalar _tmp76 = _tmp54 * _tmp66;
  const Scalar _tmp77 = -_tmp64 - _tmp76;
  const Scalar _tmp78 = _tmp1 * _tmp69;
  const Scalar _tmp79 = _tmp56 * _tmp78;
  const Scalar _tmp80 = -_tmp22 * _tmp61 - _tmp30 * _tmp77 - _tmp79 - ref_ecef(1, 0) + sv_pos(1, 0);
  const Scalar _tmp81 = 2 * _tmp80;
  const Scalar _tmp82 = _tmp54 * _tmp60;
  const Scalar _tmp83 = _tmp57 - _tmp82;
  const Scalar _tmp84 = _tmp59 * _tmp78;
  const Scalar _tmp85 = -_tmp22 * _tmp67 - _tmp30 * _tmp83 - _tmp84 - ref_ecef(0, 0) + sv_pos(0, 0);
  const Scalar _tmp86 = 2 * _tmp85;
  const Scalar _tmp87 = -_tmp62 * _tmp81 - _tmp68 * _tmp86 - _tmp70 * _tmp75;
  const Scalar _tmp88 = std::pow(_tmp73, Scalar(2)) + std::pow(_tmp80, Scalar(2)) +
                        std::pow(_tmp85, Scalar(2)) + epsilon;
  const Scalar _tmp89 = std::pow(_tmp88, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp90 = (Scalar(1) / Scalar(2)) * _tmp89;
  const Scalar _tmp91 = _tmp53 * _tmp62 - _tmp63 * _tmp68 + _tmp87 * _tmp90;
  const Scalar _tmp92 = (Scalar(1) / Scalar(2)) / (_tmp88 * std::sqrt(_tmp88));
  const Scalar _tmp93 = _tmp46 * _tmp69;
  const Scalar _tmp94 = _tmp56 * _tmp93;
  const Scalar _tmp95 = -_tmp47 * _tmp61 - _tmp48 * _tmp77 - _tmp94 + sv_vel(1, 0);
  const Scalar _tmp96 = _tmp80 * _tmp95;
  const Scalar _tmp97 = _tmp92 * _tmp96;
  const Scalar _tmp98 = _tmp59 * _tmp93;
  const Scalar _tmp99 = -_tmp47 * _tmp67 - _tmp48 * _tmp83 - _tmp98 + sv_vel(0, 0);
  const Scalar _tmp100 = _tmp85 * _tmp99;
  const Scalar _tmp101 = _tmp100 * _tmp92;
  const Scalar _tmp102 = _tmp89 * _tmp99;
  const Scalar _tmp103 = Scalar(2.4323877909897299e-13) * sv_vel(0, 0);
  const Scalar _tmp104 = Scalar(2.4323877909897299e-13) * sv_vel(1, 0);
  const Scalar _tmp105 = _tmp46 * _tmp54;
  const Scalar _tmp106 = -_tmp105 - _tmp47 * _tmp70 - _tmp48 * _tmp72 + sv_vel(2, 0);
  const Scalar _tmp107 = _tmp106 * _tmp89;
  const Scalar _tmp108 = _tmp107 * ratio;
  const Scalar _tmp109 = _tmp106 * _tmp73;
  const Scalar _tmp110 = _tmp109 * _tmp92;
  const Scalar _tmp111 = _tmp89 * _tmp95;
  const Scalar _tmp112 = _tmp111 * ratio;
  const Scalar _tmp113 = -_tmp101 * _tmp87 - _tmp102 * _tmp68 + _tmp103 * _tmp62 -
                         _tmp104 * _tmp68 - _tmp108 * _tmp70 - _tmp110 * _tmp87 - _tmp112 * _tmp61 -
                         _tmp87 * _tmp97;
  const Scalar _tmp114 = _tmp77 * ratio;
  const Scalar _tmp115 = _tmp83 * ratio;
  const Scalar _tmp116 = -_tmp114 * _tmp81 - _tmp115 * _tmp86 - _tmp72 * _tmp75;
  const Scalar _tmp117 = _tmp114 * _tmp53 - _tmp115 * _tmp63 + _tmp116 * _tmp90;
  const Scalar _tmp118 = -_tmp101 * _tmp116 - _tmp102 * _tmp115 + _tmp103 * _tmp114 -
                         _tmp104 * _tmp115 - _tmp108 * _tmp72 - _tmp110 * _tmp116 -
                         _tmp112 * _tmp77 - _tmp116 * _tmp97;
  const Scalar _tmp119 = _tmp56 * _tmp69;
  const Scalar _tmp120 = _tmp119 * ratio;
  const Scalar _tmp121 = _tmp59 * _tmp69;
  const Scalar _tmp122 = _tmp121 * ratio;
  const Scalar _tmp123 = _tmp54 * ratio;
  const Scalar _tmp124 = -_tmp120 * _tmp81 - _tmp122 * _tmp86 - _tmp123 * _tmp74;
  const Scalar _tmp125 = _tmp120 * _tmp53 - _tmp122 * _tmp63 + _tmp124 * _tmp90;
  const Scalar _tmp126 = _tmp124 * _tmp92;
  const Scalar _tmp127 = -_tmp101 * _tmp124 - _tmp102 * _tmp122 + _tmp103 * _tmp120 -
                         _tmp104 * _tmp122 - _tmp107 * _tmp123 - _tmp109 * _tmp126 -
                         _tmp112 * _tmp119 - _tmp126 * _tmp96;
  const Scalar _tmp128 = _tmp80 * _tmp89;
  const Scalar _tmp129 = _tmp85 * _tmp89;
  const Scalar _tmp130 = _tmp73 * _tmp89;
  const Scalar _tmp131 = _tmp130 * ratio;
  const Scalar _tmp132 = Scalar(2.4323877909897299e-13) * sv_pos(0, 0);
  const Scalar _tmp133 = Scalar(2.4323877909897299e-13) * sv_pos(1, 0);
  const Scalar _tmp134 =
      -_tmp128 * _tmp62 - _tmp129 * _tmp68 - _tmp131 * _tmp70 + _tmp132 * _tmp62 - _tmp133 * _tmp68;
  const Scalar _tmp135 = -_tmp114 * _tmp128 + _tmp114 * _tmp132 - _tmp115 * _tmp129 -
                         _tmp115 * _tmp133 - _tmp131 * _tmp72;
  const Scalar _tmp136 = -_tmp120 * _tmp128 + _tmp120 * _tmp132 - _tmp122 * _tmp129 -
                         _tmp122 * _tmp133 - _tmp123 * _tmp130;
  const Scalar _tmp137 = _tmp0 * _tmp63;
  const Scalar _tmp138 = _tmp0 * _tmp61;
  const Scalar _tmp139 = _tmp0 * _tmp74;
  const Scalar _tmp140 = _tmp0 * _tmp86;
  const Scalar _tmp141 = -_tmp138 * _tmp81 - _tmp139 * _tmp70 - _tmp140 * _tmp67;
  const Scalar _tmp142 = -_tmp137 * _tmp67 + _tmp138 * _tmp53 + _tmp141 * _tmp90;
  const Scalar _tmp143 = _tmp141 * _tmp92;
  const Scalar _tmp144 = _tmp0 * _tmp102;
  const Scalar _tmp145 = _tmp0 * _tmp104;
  const Scalar _tmp146 = _tmp0 * _tmp107;
  const Scalar _tmp147 = -_tmp101 * _tmp141 + _tmp103 * _tmp138 - _tmp109 * _tmp143 -
                         _tmp111 * _tmp138 - _tmp143 * _tmp96 - _tmp144 * _tmp67 -
                         _tmp145 * _tmp67 - _tmp146 * _tmp70;
  const Scalar _tmp148 = _tmp0 * _tmp77;
  const Scalar _tmp149 = -_tmp139 * _tmp72 - _tmp140 * _tmp83 - _tmp148 * _tmp81;
  const Scalar _tmp150 = -_tmp137 * _tmp83 + _tmp148 * _tmp53 + _tmp149 * _tmp90;
  const Scalar _tmp151 = -_tmp101 * _tmp149 + _tmp103 * _tmp148 - _tmp110 * _tmp149 -
                         _tmp111 * _tmp148 - _tmp144 * _tmp83 - _tmp145 * _tmp83 -
                         _tmp146 * _tmp72 - _tmp149 * _tmp97;
  const Scalar _tmp152 = _tmp0 * _tmp119;
  const Scalar _tmp153 = _tmp0 * _tmp54;
  const Scalar _tmp154 = -_tmp121 * _tmp140 - _tmp152 * _tmp81 - _tmp153 * _tmp74;
  const Scalar _tmp155 = -_tmp121 * _tmp137 + _tmp152 * _tmp53 + _tmp154 * _tmp90;
  const Scalar _tmp156 = -_tmp101 * _tmp154 + _tmp103 * _tmp152 - _tmp107 * _tmp153 -
                         _tmp110 * _tmp154 - _tmp111 * _tmp152 - _tmp121 * _tmp144 -
                         _tmp121 * _tmp145 - _tmp154 * _tmp97;
  const Scalar _tmp157 = _tmp0 * _tmp129;
  const Scalar _tmp158 = _tmp0 * _tmp130;
  const Scalar _tmp159 = _tmp0 * _tmp133;
  const Scalar _tmp160 = -_tmp128 * _tmp138 + _tmp132 * _tmp138 - _tmp157 * _tmp67 -
                         _tmp158 * _tmp70 - _tmp159 * _tmp67;
  const Scalar _tmp161 = -_tmp128 * _tmp148 + _tmp132 * _tmp148 - _tmp157 * _tmp83 -
                         _tmp158 * _tmp72 - _tmp159 * _tmp83;
  const Scalar _tmp162 = -_tmp121 * _tmp157 - _tmp121 * _tmp159 - _tmp128 * _tmp152 -
                         _tmp130 * _tmp153 + _tmp132 * _tmp152;
  const Scalar _tmp163 = _tmp58 - _tmp60;
  const Scalar _tmp164 = _tmp163 * _tmp30;
  const Scalar _tmp165 = _tmp22 * _tmp77;
  const Scalar _tmp166 = _tmp164 + _tmp165;
  const Scalar _tmp167 = -_tmp22 * _tmp72 + _tmp30 * _tmp70;
  const Scalar _tmp168 = -_tmp164 - _tmp165;
  const Scalar _tmp169 = _tmp65 + _tmp66;
  const Scalar _tmp170 = _tmp169 * _tmp30;
  const Scalar _tmp171 = _tmp22 * _tmp83;
  const Scalar _tmp172 = -_tmp170 - _tmp171;
  const Scalar _tmp173 = _tmp167 * _tmp74 + _tmp168 * _tmp81 + _tmp172 * _tmp86;
  const Scalar _tmp174 = _tmp170 + _tmp171;
  const Scalar _tmp175 = _tmp166 * _tmp53 + _tmp173 * _tmp90 - _tmp174 * _tmp63;
  const Scalar _tmp176 = _tmp173 * _tmp92;
  const Scalar _tmp177 = _tmp47 * _tmp83;
  const Scalar _tmp178 = _tmp169 * _tmp48;
  const Scalar _tmp179 = _tmp47 * _tmp77;
  const Scalar _tmp180 = _tmp163 * _tmp48;
  const Scalar _tmp181 =
      -_tmp101 * _tmp173 + _tmp102 * _tmp172 + _tmp103 * _tmp166 - _tmp104 * _tmp174 +
      _tmp107 * _tmp167 - _tmp109 * _tmp176 + _tmp111 * _tmp168 + _tmp128 * (-_tmp179 - _tmp180) +
      _tmp129 * (-_tmp177 - _tmp178) + _tmp130 * (-_tmp47 * _tmp72 + _tmp48 * _tmp70) +
      _tmp132 * (_tmp179 + _tmp180) - _tmp133 * (_tmp177 + _tmp178) - _tmp176 * _tmp96;
  const Scalar _tmp182 = Scalar(1.0) / (_tmp15);
  const Scalar _tmp183 = std::pow(_tmp9, Scalar(Scalar(-5) / Scalar(2)));
  const Scalar _tmp184 = _tmp14 * _tmp183;
  const Scalar _tmp185 = Scalar(1.3295415302198599e+39) * _tmp184;
  const Scalar _tmp186 = Scalar(3.2902684119959e+25) * _tmp10 * _tmp15;
  const Scalar _tmp187 = std::pow(_tmp16, Scalar(-2));
  const Scalar _tmp188 = _tmp13 * _tmp187;
  const Scalar _tmp189 = _tmp11 * _tmp183;
  const Scalar _tmp190 = Scalar(5.44511055670503e+52) * _tmp17 * _tmp189 * _tmp5;
  const Scalar _tmp191 = Scalar(1.0) / (std::pow(_tmp13, Scalar(2)) * _tmp187 + 1);
  const Scalar _tmp192 =
      _tmp191 *
      (-_tmp188 * (_tmp182 * ref_ecef(0, 0) + _tmp185 * ref_ecef(0, 0) - _tmp186 * ref_ecef(0, 0)) -
       _tmp190 * ref_ecef(0, 0));
  const Scalar _tmp193 = _tmp56 * _tmp71;
  const Scalar _tmp194 = _tmp192 * _tmp193;
  const Scalar _tmp195 = Scalar(1.0) / (std::pow(_tmp2, Scalar(2)) + _tmp7);
  const Scalar _tmp196 = _tmp195 * ref_ecef(1, 0);
  const Scalar _tmp197 = _tmp192 * _tmp69;
  const Scalar _tmp198 = -_tmp196 * _tmp57 + _tmp196 * _tmp82 - _tmp197 * _tmp66;
  const Scalar _tmp199 = _tmp198 * _tmp30;
  const Scalar _tmp200 = _tmp196 * _tmp65 + _tmp196 * _tmp66 - _tmp197 * _tmp57;
  const Scalar _tmp201 = _tmp200 * _tmp22;
  const Scalar _tmp202 = _tmp196 * _tmp84;
  const Scalar _tmp203 = _tmp194 - _tmp199 - _tmp201 + _tmp202;
  const Scalar _tmp204 = _tmp24 * _tmp54;
  const Scalar _tmp205 = _tmp192 * _tmp204;
  const Scalar _tmp206 = _tmp27 * _tmp54;
  const Scalar _tmp207 = _tmp192 * _tmp206;
  const Scalar _tmp208 = -_tmp192 * _tmp78 + _tmp205 * _tmp22 + _tmp207 * _tmp30;
  const Scalar _tmp209 = -_tmp196 * _tmp64 - _tmp196 * _tmp76 - _tmp197 * _tmp60;
  const Scalar _tmp210 = _tmp209 * _tmp30;
  const Scalar _tmp211 = -_tmp196 * _tmp58 + _tmp196 * _tmp60 - _tmp197 * _tmp64;
  const Scalar _tmp212 = _tmp211 * _tmp22;
  const Scalar _tmp213 = _tmp196 * _tmp79;
  const Scalar _tmp214 = _tmp59 * _tmp71;
  const Scalar _tmp215 = _tmp192 * _tmp214;
  const Scalar _tmp216 = -_tmp210 - _tmp212 - _tmp213 + _tmp215 - 1;
  const Scalar _tmp217 = _tmp203 * _tmp81 + _tmp208 * _tmp74 + _tmp216 * _tmp86;
  const Scalar _tmp218 = _tmp210 + _tmp212 + _tmp213 - _tmp215 + 1;
  const Scalar _tmp219 = -_tmp194 + _tmp199 + _tmp201 - _tmp202;
  const Scalar _tmp220 = _tmp217 * _tmp90 - _tmp218 * _tmp63 + _tmp219 * _tmp53;
  const Scalar _tmp221 = _tmp211 * _tmp47;
  const Scalar _tmp222 = _tmp209 * _tmp48;
  const Scalar _tmp223 = _tmp105 * _tmp59;
  const Scalar _tmp224 = _tmp192 * _tmp223;
  const Scalar _tmp225 = _tmp196 * _tmp94;
  const Scalar _tmp226 = _tmp217 * _tmp92;
  const Scalar _tmp227 = _tmp105 * _tmp56;
  const Scalar _tmp228 = _tmp192 * _tmp227;
  const Scalar _tmp229 = _tmp200 * _tmp47;
  const Scalar _tmp230 = _tmp198 * _tmp48;
  const Scalar _tmp231 = _tmp196 * _tmp98;
  const Scalar _tmp232 = -_tmp100 * _tmp226 + _tmp102 * _tmp216 + _tmp103 * _tmp219 -
                         _tmp104 * _tmp218 + _tmp107 * _tmp208 - _tmp109 * _tmp226 +
                         _tmp111 * _tmp203 + _tmp128 * (_tmp228 - _tmp229 - _tmp230 + _tmp231) +
                         _tmp129 * (-_tmp221 - _tmp222 + _tmp224 - _tmp225) +
                         _tmp130 * (-_tmp192 * _tmp93 + _tmp205 * _tmp47 + _tmp207 * _tmp48) +
                         _tmp132 * (-_tmp228 + _tmp229 + _tmp230 - _tmp231) -
                         _tmp133 * (_tmp221 + _tmp222 - _tmp224 + _tmp225) - _tmp226 * _tmp96;
  const Scalar _tmp233 = _tmp195 * _tmp2;
  const Scalar _tmp234 = _tmp233 * _tmp84;
  const Scalar _tmp235 =
      _tmp191 *
      (-_tmp188 * (_tmp182 * ref_ecef(1, 0) + _tmp185 * ref_ecef(1, 0) - _tmp186 * ref_ecef(1, 0)) -
       _tmp190 * ref_ecef(1, 0));
  const Scalar _tmp236 = _tmp235 * _tmp69;
  const Scalar _tmp237 = -_tmp233 * _tmp65 - _tmp233 * _tmp66 - _tmp236 * _tmp57;
  const Scalar _tmp238 = _tmp22 * _tmp237;
  const Scalar _tmp239 = _tmp233 * _tmp57 - _tmp233 * _tmp82 - _tmp236 * _tmp66;
  const Scalar _tmp240 = _tmp239 * _tmp30;
  const Scalar _tmp241 = _tmp193 * _tmp235;
  const Scalar _tmp242 = -_tmp234 - _tmp238 - _tmp240 + _tmp241 - 1;
  const Scalar _tmp243 = _tmp204 * _tmp22;
  const Scalar _tmp244 = _tmp206 * _tmp30;
  const Scalar _tmp245 = _tmp235 * _tmp243 + _tmp235 * _tmp244 - _tmp235 * _tmp78;
  const Scalar _tmp246 = _tmp214 * _tmp235;
  const Scalar _tmp247 = _tmp233 * _tmp79;
  const Scalar _tmp248 = _tmp233 * _tmp58 - _tmp233 * _tmp60 - _tmp236 * _tmp64;
  const Scalar _tmp249 = _tmp22 * _tmp248;
  const Scalar _tmp250 = _tmp233 * _tmp64 + _tmp233 * _tmp76 - _tmp236 * _tmp60;
  const Scalar _tmp251 = _tmp250 * _tmp30;
  const Scalar _tmp252 = _tmp246 + _tmp247 - _tmp249 - _tmp251;
  const Scalar _tmp253 = _tmp242 * _tmp81 + _tmp245 * _tmp74 + _tmp252 * _tmp86;
  const Scalar _tmp254 = _tmp234 + _tmp238 + _tmp240 - _tmp241 + 1;
  const Scalar _tmp255 = -_tmp246 - _tmp247 + _tmp249 + _tmp251;
  const Scalar _tmp256 = _tmp253 * _tmp90 + _tmp254 * _tmp53 - _tmp255 * _tmp63;
  const Scalar _tmp257 = _tmp250 * _tmp48;
  const Scalar _tmp258 = _tmp248 * _tmp47;
  const Scalar _tmp259 = _tmp233 * _tmp94;
  const Scalar _tmp260 = _tmp223 * _tmp235;
  const Scalar _tmp261 = _tmp233 * _tmp98;
  const Scalar _tmp262 = _tmp227 * _tmp235;
  const Scalar _tmp263 = _tmp239 * _tmp48;
  const Scalar _tmp264 = _tmp237 * _tmp47;
  const Scalar _tmp265 = _tmp204 * _tmp47;
  const Scalar _tmp266 =
      -_tmp101 * _tmp253 + _tmp102 * _tmp252 + _tmp103 * _tmp254 - _tmp104 * _tmp255 +
      _tmp107 * _tmp245 - _tmp110 * _tmp253 + _tmp111 * _tmp242 +
      _tmp128 * (-_tmp261 + _tmp262 - _tmp263 - _tmp264) +
      _tmp129 * (-_tmp257 - _tmp258 + _tmp259 + _tmp260) +
      _tmp130 * (_tmp206 * _tmp235 * _tmp48 + _tmp235 * _tmp265 - _tmp235 * _tmp93) +
      _tmp132 * (_tmp261 - _tmp262 + _tmp263 + _tmp264) -
      _tmp133 * (_tmp257 + _tmp258 - _tmp259 - _tmp260) - _tmp253 * _tmp97;
  const Scalar _tmp267 =
      _tmp191 *
      (_tmp17 * (Scalar(1.34752280070479e+39) * _tmp12 * _tmp6 -
                 Scalar(5.4818078615632705e+52) * _tmp189 * std::pow(ref_ecef(2, 0), Scalar(4)) +
                 Scalar(1.0)) -
       Scalar(1.3385019710315001e+39) * _tmp184 * _tmp188 * ref_ecef(2, 0));
  const Scalar _tmp268 = _tmp267 * _tmp69;
  const Scalar _tmp269 = _tmp22 * _tmp268;
  const Scalar _tmp270 = _tmp269 * _tmp64;
  const Scalar _tmp271 = _tmp268 * _tmp30;
  const Scalar _tmp272 = _tmp271 * _tmp60;
  const Scalar _tmp273 = _tmp214 * _tmp267;
  const Scalar _tmp274 = -_tmp270 - _tmp272 - _tmp273;
  const Scalar _tmp275 = _tmp193 * _tmp267;
  const Scalar _tmp276 = _tmp271 * _tmp66;
  const Scalar _tmp277 = _tmp269 * _tmp57;
  const Scalar _tmp278 = -_tmp275 - _tmp276 - _tmp277;
  const Scalar _tmp279 = _tmp270 + _tmp272 + _tmp273;
  const Scalar _tmp280 = _tmp243 * _tmp267 + _tmp244 * _tmp267 - _tmp267 * _tmp78 - 1;
  const Scalar _tmp281 = _tmp275 + _tmp276 + _tmp277;
  const Scalar _tmp282 = _tmp279 * _tmp86 + _tmp280 * _tmp74 + _tmp281 * _tmp81;
  const Scalar _tmp283 = -_tmp274 * _tmp63 + _tmp278 * _tmp53 + _tmp282 * _tmp90;
  const Scalar _tmp284 = _tmp223 * _tmp267;
  const Scalar _tmp285 = _tmp268 * _tmp47;
  const Scalar _tmp286 = _tmp285 * _tmp64;
  const Scalar _tmp287 = _tmp267 * _tmp48;
  const Scalar _tmp288 = _tmp287 * _tmp69;
  const Scalar _tmp289 = _tmp288 * _tmp60;
  const Scalar _tmp290 = _tmp288 * _tmp66;
  const Scalar _tmp291 = _tmp285 * _tmp57;
  const Scalar _tmp292 = _tmp227 * _tmp267;
  const Scalar _tmp293 = -_tmp101 * _tmp282 + _tmp102 * _tmp279 + _tmp103 * _tmp278 -
                         _tmp104 * _tmp274 + _tmp107 * _tmp280 - _tmp110 * _tmp282 +
                         _tmp111 * _tmp281 + _tmp128 * (_tmp290 + _tmp291 + _tmp292) +
                         _tmp129 * (_tmp284 + _tmp286 + _tmp289) +
                         _tmp130 * (_tmp206 * _tmp287 + _tmp265 * _tmp267 - _tmp267 * _tmp93) +
                         _tmp132 * (-_tmp290 - _tmp291 - _tmp292) -
                         _tmp133 * (-_tmp284 - _tmp286 - _tmp289) - _tmp282 * _tmp97;
  const Scalar _tmp294 = std::pow(dp_weight, Scalar(2));
  const Scalar _tmp295 = std::pow(pr_weight, Scalar(2));
  const Scalar _tmp296 = _tmp118 * _tmp294;
  const Scalar _tmp297 = _tmp117 * _tmp295;
  const Scalar _tmp298 = _tmp125 * _tmp295;
  const Scalar _tmp299 = _tmp113 * _tmp294;
  const Scalar _tmp300 = _tmp134 * _tmp294;
  const Scalar _tmp301 = _tmp135 * _tmp294;
  const Scalar _tmp302 = _tmp136 * _tmp294;
  const Scalar _tmp303 = _tmp295 * _tmp91;
  const Scalar _tmp304 = _tmp147 * _tmp294;
  const Scalar _tmp305 = _tmp151 * _tmp294;
  const Scalar _tmp306 = _tmp150 * _tmp295;
  const Scalar _tmp307 = _tmp155 * _tmp295;
  const Scalar _tmp308 = _tmp156 * _tmp294;
  const Scalar _tmp309 = _tmp160 * _tmp294;
  const Scalar _tmp310 = _tmp161 * _tmp294;
  const Scalar _tmp311 = _tmp162 * _tmp294;
  const Scalar _tmp312 = _tmp181 * _tmp294;
  const Scalar _tmp313 = _tmp232 * _tmp294;
  const Scalar _tmp314 = _tmp220 * _tmp295;
  const Scalar _tmp315 = _tmp266 * _tmp294;
  const Scalar _tmp316 = _tmp293 * _tmp294;
  const Scalar _tmp317 = _tmp142 * _tmp295;
  const Scalar _tmp318 = _tmp175 * _tmp295;
  const Scalar _tmp319 = _tmp256 * _tmp295;
  const Scalar _tmp320 = _tmp294 * _tmp52;
  const Scalar _tmp321 = _tmp295 * _tmp45;

  // Output terms (4)
  if (res != nullptr) {
    Eigen::Matrix<Scalar, 2, 1>& _res = (*res);

    _res(0, 0) = _tmp45 * pr_weight;
    _res(1, 0) = _tmp52 * dp_weight;
  }

  if (jacobian != nullptr) {
    Eigen::Matrix<Scalar, 2, 18>& _jacobian = (*jacobian);

    _jacobian(0, 0) = _tmp91 * pr_weight;
    _jacobian(1, 0) = _tmp113 * dp_weight;
    _jacobian(0, 1) = _tmp117 * pr_weight;
    _jacobian(1, 1) = _tmp118 * dp_weight;
    _jacobian(0, 2) = _tmp125 * pr_weight;
    _jacobian(1, 2) = _tmp127 * dp_weight;
    _jacobian(0, 3) = 0;
    _jacobian(1, 3) = _tmp134 * dp_weight;
    _jacobian(0, 4) = 0;
    _jacobian(1, 4) = _tmp135 * dp_weight;
    _jacobian(0, 5) = 0;
    _jacobian(1, 5) = _tmp136 * dp_weight;
    _jacobian(0, 6) = _tmp142 * pr_weight;
    _jacobian(1, 6) = _tmp147 * dp_weight;
    _jacobian(0, 7) = _tmp150 * pr_weight;
    _jacobian(1, 7) = _tmp151 * dp_weight;
    _jacobian(0, 8) = _tmp155 * pr_weight;
    _jacobian(1, 8) = _tmp156 * dp_weight;
    _jacobian(0, 9) = 0;
    _jacobian(1, 9) = _tmp160 * dp_weight;
    _jacobian(0, 10) = 0;
    _jacobian(1, 10) = _tmp161 * dp_weight;
    _jacobian(0, 11) = 0;
    _jacobian(1, 11) = _tmp162 * dp_weight;
    _jacobian(0, 12) = pr_weight;
    _jacobian(1, 12) = 0;
    _jacobian(0, 13) = 0;
    _jacobian(1, 13) = dp_weight;
    _jacobian(0, 14) = _tmp175 * pr_weight;
    _jacobian(1, 14) = _tmp181 * dp_weight;
    _jacobian(0, 15) = _tmp220 * pr_weight;
    _jacobian(1, 15) = _tmp232 * dp_weight;
    _jacobian(0, 16) = _tmp256 * pr_weight;
    _jacobian(1, 16) = _tmp266 * dp_weight;
    _jacobian(0, 17) = _tmp283 * pr_weight;
    _jacobian(1, 17) = _tmp293 * dp_weight;
  }

  if (hessian != nullptr) {
    Eigen::Matrix<Scalar, 18, 18>& _hessian = (*hessian);

    _hessian(0, 0) = std::pow(_tmp113, Scalar(2)) * _tmp294 + _tmp295 * std::pow(_tmp91, Scalar(2));
    _hessian(1, 0) = _tmp113 * _tmp296 + _tmp297 * _tmp91;
    _hessian(2, 0) = _tmp127 * _tmp299 + _tmp298 * _tmp91;
    _hessian(3, 0) = _tmp113 * _tmp300;
    _hessian(4, 0) = _tmp113 * _tmp301;
    _hessian(5, 0) = _tmp113 * _tmp302;
    _hessian(6, 0) = _tmp113 * _tmp304 + _tmp142 * _tmp303;
    _hessian(7, 0) = _tmp113 * _tmp305 + _tmp306 * _tmp91;
    _hessian(8, 0) = _tmp113 * _tmp308 + _tmp307 * _tmp91;
    _hessian(9, 0) = _tmp113 * _tmp309;
    _hessian(10, 0) = _tmp113 * _tmp310;
    _hessian(11, 0) = _tmp113 * _tmp311;
    _hessian(12, 0) = _tmp303;
    _hessian(13, 0) = _tmp299;
    _hessian(14, 0) = _tmp113 * _tmp312 + _tmp175 * _tmp303;
    _hessian(15, 0) = _tmp113 * _tmp313 + _tmp314 * _tmp91;
    _hessian(16, 0) = _tmp113 * _tmp315 + _tmp256 * _tmp303;
    _hessian(17, 0) = _tmp113 * _tmp316 + _tmp283 * _tmp303;
    _hessian(0, 1) = 0;
    _hessian(1, 1) =
        std::pow(_tmp117, Scalar(2)) * _tmp295 + std::pow(_tmp118, Scalar(2)) * _tmp294;
    _hessian(2, 1) = _tmp117 * _tmp298 + _tmp127 * _tmp296;
    _hessian(3, 1) = _tmp118 * _tmp300;
    _hessian(4, 1) = _tmp135 * _tmp296;
    _hessian(5, 1) = _tmp136 * _tmp296;
    _hessian(6, 1) = _tmp142 * _tmp297 + _tmp147 * _tmp296;
    _hessian(7, 1) = _tmp117 * _tmp306 + _tmp151 * _tmp296;
    _hessian(8, 1) = _tmp117 * _tmp307 + _tmp118 * _tmp308;
    _hessian(9, 1) = _tmp118 * _tmp309;
    _hessian(10, 1) = _tmp118 * _tmp310;
    _hessian(11, 1) = _tmp162 * _tmp296;
    _hessian(12, 1) = _tmp297;
    _hessian(13, 1) = _tmp296;
    _hessian(14, 1) = _tmp175 * _tmp297 + _tmp181 * _tmp296;
    _hessian(15, 1) = _tmp117 * _tmp314 + _tmp232 * _tmp296;
    _hessian(16, 1) = _tmp118 * _tmp315 + _tmp256 * _tmp297;
    _hessian(17, 1) = _tmp118 * _tmp316 + _tmp283 * _tmp297;
    _hessian(0, 2) = 0;
    _hessian(1, 2) = 0;
    _hessian(2, 2) =
        std::pow(_tmp125, Scalar(2)) * _tmp295 + std::pow(_tmp127, Scalar(2)) * _tmp294;
    _hessian(3, 2) = _tmp127 * _tmp300;
    _hessian(4, 2) = _tmp127 * _tmp301;
    _hessian(5, 2) = _tmp127 * _tmp302;
    _hessian(6, 2) = _tmp127 * _tmp304 + _tmp142 * _tmp298;
    _hessian(7, 2) = _tmp127 * _tmp305 + _tmp150 * _tmp298;
    _hessian(8, 2) = _tmp127 * _tmp308 + _tmp155 * _tmp298;
    _hessian(9, 2) = _tmp127 * _tmp309;
    _hessian(10, 2) = _tmp127 * _tmp310;
    _hessian(11, 2) = _tmp127 * _tmp311;
    _hessian(12, 2) = _tmp298;
    _hessian(13, 2) = _tmp127 * _tmp294;
    _hessian(14, 2) = _tmp127 * _tmp312 + _tmp175 * _tmp298;
    _hessian(15, 2) = _tmp127 * _tmp313 + _tmp220 * _tmp298;
    _hessian(16, 2) = _tmp127 * _tmp315 + _tmp256 * _tmp298;
    _hessian(17, 2) = _tmp127 * _tmp316 + _tmp283 * _tmp298;
    _hessian(0, 3) = 0;
    _hessian(1, 3) = 0;
    _hessian(2, 3) = 0;
    _hessian(3, 3) = std::pow(_tmp134, Scalar(2)) * _tmp294;
    _hessian(4, 3) = _tmp135 * _tmp300;
    _hessian(5, 3) = _tmp136 * _tmp300;
    _hessian(6, 3) = _tmp147 * _tmp300;
    _hessian(7, 3) = _tmp151 * _tmp300;
    _hessian(8, 3) = _tmp156 * _tmp300;
    _hessian(9, 3) = _tmp160 * _tmp300;
    _hessian(10, 3) = _tmp161 * _tmp300;
    _hessian(11, 3) = _tmp162 * _tmp300;
    _hessian(12, 3) = 0;
    _hessian(13, 3) = _tmp300;
    _hessian(14, 3) = _tmp181 * _tmp300;
    _hessian(15, 3) = _tmp232 * _tmp300;
    _hessian(16, 3) = _tmp266 * _tmp300;
    _hessian(17, 3) = _tmp293 * _tmp300;
    _hessian(0, 4) = 0;
    _hessian(1, 4) = 0;
    _hessian(2, 4) = 0;
    _hessian(3, 4) = 0;
    _hessian(4, 4) = std::pow(_tmp135, Scalar(2)) * _tmp294;
    _hessian(5, 4) = _tmp136 * _tmp301;
    _hessian(6, 4) = _tmp147 * _tmp301;
    _hessian(7, 4) = _tmp135 * _tmp305;
    _hessian(8, 4) = _tmp135 * _tmp308;
    _hessian(9, 4) = _tmp135 * _tmp309;
    _hessian(10, 4) = _tmp135 * _tmp310;
    _hessian(11, 4) = _tmp135 * _tmp311;
    _hessian(12, 4) = 0;
    _hessian(13, 4) = _tmp301;
    _hessian(14, 4) = _tmp135 * _tmp312;
    _hessian(15, 4) = _tmp232 * _tmp301;
    _hessian(16, 4) = _tmp135 * _tmp315;
    _hessian(17, 4) = _tmp135 * _tmp316;
    _hessian(0, 5) = 0;
    _hessian(1, 5) = 0;
    _hessian(2, 5) = 0;
    _hessian(3, 5) = 0;
    _hessian(4, 5) = 0;
    _hessian(5, 5) = std::pow(_tmp136, Scalar(2)) * _tmp294;
    _hessian(6, 5) = _tmp136 * _tmp304;
    _hessian(7, 5) = _tmp136 * _tmp305;
    _hessian(8, 5) = _tmp136 * _tmp308;
    _hessian(9, 5) = _tmp136 * _tmp309;
    _hessian(10, 5) = _tmp136 * _tmp310;
    _hessian(11, 5) = _tmp136 * _tmp311;
    _hessian(12, 5) = 0;
    _hessian(13, 5) = _tmp302;
    _hessian(14, 5) = _tmp136 * _tmp312;
    _hessian(15, 5) = _tmp136 * _tmp313;
    _hessian(16, 5) = _tmp136 * _tmp315;
    _hessian(17, 5) = _tmp136 * _tmp316;
    _hessian(0, 6) = 0;
    _hessian(1, 6) = 0;
    _hessian(2, 6) = 0;
    _hessian(3, 6) = 0;
    _hessian(4, 6) = 0;
    _hessian(5, 6) = 0;
    _hessian(6, 6) =
        std::pow(_tmp142, Scalar(2)) * _tmp295 + std::pow(_tmp147, Scalar(2)) * _tmp294;
    _hessian(7, 6) = _tmp142 * _tmp306 + _tmp147 * _tmp305;
    _hessian(8, 6) = _tmp142 * _tmp307 + _tmp147 * _tmp308;
    _hessian(9, 6) = _tmp147 * _tmp309;
    _hessian(10, 6) = _tmp147 * _tmp310;
    _hessian(11, 6) = _tmp147 * _tmp311;
    _hessian(12, 6) = _tmp317;
    _hessian(13, 6) = _tmp304;
    _hessian(14, 6) = _tmp142 * _tmp318 + _tmp147 * _tmp312;
    _hessian(15, 6) = _tmp142 * _tmp314 + _tmp147 * _tmp313;
    _hessian(16, 6) = _tmp142 * _tmp319 + _tmp147 * _tmp315;
    _hessian(17, 6) = _tmp147 * _tmp316 + _tmp283 * _tmp317;
    _hessian(0, 7) = 0;
    _hessian(1, 7) = 0;
    _hessian(2, 7) = 0;
    _hessian(3, 7) = 0;
    _hessian(4, 7) = 0;
    _hessian(5, 7) = 0;
    _hessian(6, 7) = 0;
    _hessian(7, 7) =
        std::pow(_tmp150, Scalar(2)) * _tmp295 + std::pow(_tmp151, Scalar(2)) * _tmp294;
    _hessian(8, 7) = _tmp151 * _tmp308 + _tmp155 * _tmp306;
    _hessian(9, 7) = _tmp151 * _tmp309;
    _hessian(10, 7) = _tmp151 * _tmp310;
    _hessian(11, 7) = _tmp151 * _tmp311;
    _hessian(12, 7) = _tmp306;
    _hessian(13, 7) = _tmp305;
    _hessian(14, 7) = _tmp175 * _tmp306 + _tmp181 * _tmp305;
    _hessian(15, 7) = _tmp150 * _tmp314 + _tmp232 * _tmp305;
    _hessian(16, 7) = _tmp151 * _tmp315 + _tmp256 * _tmp306;
    _hessian(17, 7) = _tmp151 * _tmp316 + _tmp283 * _tmp306;
    _hessian(0, 8) = 0;
    _hessian(1, 8) = 0;
    _hessian(2, 8) = 0;
    _hessian(3, 8) = 0;
    _hessian(4, 8) = 0;
    _hessian(5, 8) = 0;
    _hessian(6, 8) = 0;
    _hessian(7, 8) = 0;
    _hessian(8, 8) =
        std::pow(_tmp155, Scalar(2)) * _tmp295 + std::pow(_tmp156, Scalar(2)) * _tmp294;
    _hessian(9, 8) = _tmp160 * _tmp308;
    _hessian(10, 8) = _tmp161 * _tmp308;
    _hessian(11, 8) = _tmp162 * _tmp308;
    _hessian(12, 8) = _tmp307;
    _hessian(13, 8) = _tmp308;
    _hessian(14, 8) = _tmp175 * _tmp307 + _tmp181 * _tmp308;
    _hessian(15, 8) = _tmp155 * _tmp314 + _tmp232 * _tmp308;
    _hessian(16, 8) = _tmp256 * _tmp307 + _tmp266 * _tmp308;
    _hessian(17, 8) = _tmp283 * _tmp307 + _tmp293 * _tmp308;
    _hessian(0, 9) = 0;
    _hessian(1, 9) = 0;
    _hessian(2, 9) = 0;
    _hessian(3, 9) = 0;
    _hessian(4, 9) = 0;
    _hessian(5, 9) = 0;
    _hessian(6, 9) = 0;
    _hessian(7, 9) = 0;
    _hessian(8, 9) = 0;
    _hessian(9, 9) = std::pow(_tmp160, Scalar(2)) * _tmp294;
    _hessian(10, 9) = _tmp161 * _tmp309;
    _hessian(11, 9) = _tmp162 * _tmp309;
    _hessian(12, 9) = 0;
    _hessian(13, 9) = _tmp309;
    _hessian(14, 9) = _tmp181 * _tmp309;
    _hessian(15, 9) = _tmp232 * _tmp309;
    _hessian(16, 9) = _tmp160 * _tmp315;
    _hessian(17, 9) = _tmp160 * _tmp316;
    _hessian(0, 10) = 0;
    _hessian(1, 10) = 0;
    _hessian(2, 10) = 0;
    _hessian(3, 10) = 0;
    _hessian(4, 10) = 0;
    _hessian(5, 10) = 0;
    _hessian(6, 10) = 0;
    _hessian(7, 10) = 0;
    _hessian(8, 10) = 0;
    _hessian(9, 10) = 0;
    _hessian(10, 10) = std::pow(_tmp161, Scalar(2)) * _tmp294;
    _hessian(11, 10) = _tmp162 * _tmp310;
    _hessian(12, 10) = 0;
    _hessian(13, 10) = _tmp310;
    _hessian(14, 10) = _tmp181 * _tmp310;
    _hessian(15, 10) = _tmp232 * _tmp310;
    _hessian(16, 10) = _tmp161 * _tmp315;
    _hessian(17, 10) = _tmp161 * _tmp316;
    _hessian(0, 11) = 0;
    _hessian(1, 11) = 0;
    _hessian(2, 11) = 0;
    _hessian(3, 11) = 0;
    _hessian(4, 11) = 0;
    _hessian(5, 11) = 0;
    _hessian(6, 11) = 0;
    _hessian(7, 11) = 0;
    _hessian(8, 11) = 0;
    _hessian(9, 11) = 0;
    _hessian(10, 11) = 0;
    _hessian(11, 11) = std::pow(_tmp162, Scalar(2)) * _tmp294;
    _hessian(12, 11) = 0;
    _hessian(13, 11) = _tmp311;
    _hessian(14, 11) = _tmp181 * _tmp311;
    _hessian(15, 11) = _tmp232 * _tmp311;
    _hessian(16, 11) = _tmp162 * _tmp315;
    _hessian(17, 11) = _tmp162 * _tmp316;
    _hessian(0, 12) = 0;
    _hessian(1, 12) = 0;
    _hessian(2, 12) = 0;
    _hessian(3, 12) = 0;
    _hessian(4, 12) = 0;
    _hessian(5, 12) = 0;
    _hessian(6, 12) = 0;
    _hessian(7, 12) = 0;
    _hessian(8, 12) = 0;
    _hessian(9, 12) = 0;
    _hessian(10, 12) = 0;
    _hessian(11, 12) = 0;
    _hessian(12, 12) = _tmp295;
    _hessian(13, 12) = 0;
    _hessian(14, 12) = _tmp318;
    _hessian(15, 12) = _tmp314;
    _hessian(16, 12) = _tmp319;
    _hessian(17, 12) = _tmp283 * _tmp295;
    _hessian(0, 13) = 0;
    _hessian(1, 13) = 0;
    _hessian(2, 13) = 0;
    _hessian(3, 13) = 0;
    _hessian(4, 13) = 0;
    _hessian(5, 13) = 0;
    _hessian(6, 13) = 0;
    _hessian(7, 13) = 0;
    _hessian(8, 13) = 0;
    _hessian(9, 13) = 0;
    _hessian(10, 13) = 0;
    _hessian(11, 13) = 0;
    _hessian(12, 13) = 0;
    _hessian(13, 13) = _tmp294;
    _hessian(14, 13) = _tmp312;
    _hessian(15, 13) = _tmp313;
    _hessian(16, 13) = _tmp315;
    _hessian(17, 13) = _tmp316;
    _hessian(0, 14) = 0;
    _hessian(1, 14) = 0;
    _hessian(2, 14) = 0;
    _hessian(3, 14) = 0;
    _hessian(4, 14) = 0;
    _hessian(5, 14) = 0;
    _hessian(6, 14) = 0;
    _hessian(7, 14) = 0;
    _hessian(8, 14) = 0;
    _hessian(9, 14) = 0;
    _hessian(10, 14) = 0;
    _hessian(11, 14) = 0;
    _hessian(12, 14) = 0;
    _hessian(13, 14) = 0;
    _hessian(14, 14) =
        std::pow(_tmp175, Scalar(2)) * _tmp295 + std::pow(_tmp181, Scalar(2)) * _tmp294;
    _hessian(15, 14) = _tmp175 * _tmp314 + _tmp232 * _tmp312;
    _hessian(16, 14) = _tmp175 * _tmp319 + _tmp181 * _tmp315;
    _hessian(17, 14) = _tmp181 * _tmp316 + _tmp283 * _tmp318;
    _hessian(0, 15) = 0;
    _hessian(1, 15) = 0;
    _hessian(2, 15) = 0;
    _hessian(3, 15) = 0;
    _hessian(4, 15) = 0;
    _hessian(5, 15) = 0;
    _hessian(6, 15) = 0;
    _hessian(7, 15) = 0;
    _hessian(8, 15) = 0;
    _hessian(9, 15) = 0;
    _hessian(10, 15) = 0;
    _hessian(11, 15) = 0;
    _hessian(12, 15) = 0;
    _hessian(13, 15) = 0;
    _hessian(14, 15) = 0;
    _hessian(15, 15) =
        std::pow(_tmp220, Scalar(2)) * _tmp295 + std::pow(_tmp232, Scalar(2)) * _tmp294;
    _hessian(16, 15) = _tmp232 * _tmp315 + _tmp256 * _tmp314;
    _hessian(17, 15) = _tmp232 * _tmp316 + _tmp283 * _tmp314;
    _hessian(0, 16) = 0;
    _hessian(1, 16) = 0;
    _hessian(2, 16) = 0;
    _hessian(3, 16) = 0;
    _hessian(4, 16) = 0;
    _hessian(5, 16) = 0;
    _hessian(6, 16) = 0;
    _hessian(7, 16) = 0;
    _hessian(8, 16) = 0;
    _hessian(9, 16) = 0;
    _hessian(10, 16) = 0;
    _hessian(11, 16) = 0;
    _hessian(12, 16) = 0;
    _hessian(13, 16) = 0;
    _hessian(14, 16) = 0;
    _hessian(15, 16) = 0;
    _hessian(16, 16) =
        std::pow(_tmp256, Scalar(2)) * _tmp295 + std::pow(_tmp266, Scalar(2)) * _tmp294;
    _hessian(17, 16) = _tmp283 * _tmp319 + _tmp293 * _tmp315;
    _hessian(0, 17) = 0;
    _hessian(1, 17) = 0;
    _hessian(2, 17) = 0;
    _hessian(3, 17) = 0;
    _hessian(4, 17) = 0;
    _hessian(5, 17) = 0;
    _hessian(6, 17) = 0;
    _hessian(7, 17) = 0;
    _hessian(8, 17) = 0;
    _hessian(9, 17) = 0;
    _hessian(10, 17) = 0;
    _hessian(11, 17) = 0;
    _hessian(12, 17) = 0;
    _hessian(13, 17) = 0;
    _hessian(14, 17) = 0;
    _hessian(15, 17) = 0;
    _hessian(16, 17) = 0;
    _hessian(17, 17) =
        std::pow(_tmp283, Scalar(2)) * _tmp295 + std::pow(_tmp293, Scalar(2)) * _tmp294;
  }

  if (rhs != nullptr) {
    Eigen::Matrix<Scalar, 18, 1>& _rhs = (*rhs);

    _rhs(0, 0) = _tmp299 * _tmp52 + _tmp303 * _tmp45;
    _rhs(1, 0) = _tmp296 * _tmp52 + _tmp297 * _tmp45;
    _rhs(2, 0) = _tmp127 * _tmp320 + _tmp298 * _tmp45;
    _rhs(3, 0) = _tmp300 * _tmp52;
    _rhs(4, 0) = _tmp301 * _tmp52;
    _rhs(5, 0) = _tmp302 * _tmp52;
    _rhs(6, 0) = _tmp142 * _tmp321 + _tmp304 * _tmp52;
    _rhs(7, 0) = _tmp305 * _tmp52 + _tmp306 * _tmp45;
    _rhs(8, 0) = _tmp307 * _tmp45 + _tmp308 * _tmp52;
    _rhs(9, 0) = _tmp309 * _tmp52;
    _rhs(10, 0) = _tmp310 * _tmp52;
    _rhs(11, 0) = _tmp311 * _tmp52;
    _rhs(12, 0) = _tmp321;
    _rhs(13, 0) = _tmp320;
    _rhs(14, 0) = _tmp175 * _tmp321 + _tmp312 * _tmp52;
    _rhs(15, 0) = _tmp313 * _tmp52 + _tmp314 * _tmp45;
    _rhs(16, 0) = _tmp256 * _tmp321 + _tmp315 * _tmp52;
    _rhs(17, 0) = _tmp283 * _tmp321 + _tmp316 * _tmp52;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
