// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: max3
 *
 * Args:
 *     a: Scalar
 *     b: Scalar
 *
 * Outputs:
 *     res: Scalar
 */
template <typename Scalar>
Scalar Max3(const Scalar a, const Scalar b) {
  // Total ops: 1

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  Scalar _res;

  _res = std::max<Scalar>(a, b);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
