// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: max4
 *
 * Args:
 *     a: Scalar
 *     b: Scalar
 *
 * Outputs:
 *     res: Scalar
 */
template <typename Scalar>
Scalar Max4(const Scalar a, const Scalar b) {
  // Total ops: 5

  // Input arrays

  // Intermediate terms (1)
  const Scalar _tmp0 = a - b;

  // Output terms (1)
  Scalar _res;

  _res = _tmp0 * std::max<Scalar>(0, (((_tmp0) > 0) - ((_tmp0) < 0))) + b;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
