// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: projection_residual
 *
 * Args:
 *     pts_i: Matrix31
 *     pts_j: Matrix31
 *     Pi: Matrix31
 *     Qi: Rot3
 *     Pj: Matrix31
 *     Qj: Rot3
 *     tic: Matrix31
 *     qic: Rot3
 *     inv_dep_i: Scalar
 *
 * Outputs:
 *     res: Matrix21
 *     jacobian: (2x19) jacobian of res wrt args Pi (3), Qi (3), Pj (3), Qj (3), tic (3), qic (3),
 *               inv_dep_i (1)
 *     hessian: (19x19) Gauss-Newton hessian for args Pi (3), Qi (3), Pj (3), Qj (3), tic (3), qic
 *              (3), inv_dep_i (1)
 *     rhs: (19x1) Gauss-Newton rhs for args Pi (3), Qi (3), Pj (3), Qj (3), tic (3), qic (3),
 *          inv_dep_i (1)
 */
template <typename Scalar>
void ProjectionFactor(const Eigen::Matrix<Scalar, 3, 1>& pts_i,
                      const Eigen::Matrix<Scalar, 3, 1>& pts_j,
                      const Eigen::Matrix<Scalar, 3, 1>& Pi, const sym::Rot3<Scalar>& Qi,
                      const Eigen::Matrix<Scalar, 3, 1>& Pj, const sym::Rot3<Scalar>& Qj,
                      const Eigen::Matrix<Scalar, 3, 1>& tic, const sym::Rot3<Scalar>& qic,
                      const Scalar inv_dep_i, Eigen::Matrix<Scalar, 2, 1>* const res = nullptr,
                      Eigen::Matrix<Scalar, 2, 19>* const jacobian = nullptr,
                      Eigen::Matrix<Scalar, 19, 19>* const hessian = nullptr,
                      Eigen::Matrix<Scalar, 19, 1>* const rhs = nullptr) {
  // Total ops: 1702

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _Qi = Qi.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Qj = Qj.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _qic = qic.Data();

  // Intermediate terms (373)
  const Scalar _tmp0 = std::pow(_qic[2], Scalar(2));
  const Scalar _tmp1 = -2 * _tmp0;
  const Scalar _tmp2 = std::pow(_qic[1], Scalar(2));
  const Scalar _tmp3 = 1 - 2 * _tmp2;
  const Scalar _tmp4 = _tmp1 + _tmp3;
  const Scalar _tmp5 = std::pow(_Qj[1], Scalar(2));
  const Scalar _tmp6 = -2 * _tmp5;
  const Scalar _tmp7 = std::pow(_Qj[2], Scalar(2));
  const Scalar _tmp8 = -2 * _tmp7;
  const Scalar _tmp9 = _tmp6 + _tmp8 + 1;
  const Scalar _tmp10 = 2 * _Qi[1];
  const Scalar _tmp11 = _Qi[0] * _tmp10;
  const Scalar _tmp12 = 2 * _Qi[2];
  const Scalar _tmp13 = _Qi[3] * _tmp12;
  const Scalar _tmp14 = -_tmp13;
  const Scalar _tmp15 = _tmp11 + _tmp14;
  const Scalar _tmp16 = std::pow(_qic[0], Scalar(2));
  const Scalar _tmp17 = -2 * _tmp16;
  const Scalar _tmp18 = _tmp1 + _tmp17 + 1;
  const Scalar _tmp19 = Scalar(1.0) / (inv_dep_i);
  const Scalar _tmp20 = _tmp19 * pts_i(1, 0);
  const Scalar _tmp21 = 2 * _qic[3];
  const Scalar _tmp22 = _qic[0] * _tmp21;
  const Scalar _tmp23 = -_tmp22;
  const Scalar _tmp24 = 2 * _qic[1];
  const Scalar _tmp25 = _qic[2] * _tmp24;
  const Scalar _tmp26 = _tmp23 + _tmp25;
  const Scalar _tmp27 = _tmp19 * pts_i(2, 0);
  const Scalar _tmp28 = _qic[2] * _tmp21;
  const Scalar _tmp29 = _qic[0] * _tmp24;
  const Scalar _tmp30 = _tmp28 + _tmp29;
  const Scalar _tmp31 = _tmp19 * pts_i(0, 0);
  const Scalar _tmp32 = _tmp18 * _tmp20 + _tmp26 * _tmp27 + _tmp30 * _tmp31 + tic(1, 0);
  const Scalar _tmp33 = std::pow(_Qi[2], Scalar(2));
  const Scalar _tmp34 = -2 * _tmp33;
  const Scalar _tmp35 = std::pow(_Qi[1], Scalar(2));
  const Scalar _tmp36 = -2 * _tmp35;
  const Scalar _tmp37 = _tmp34 + _tmp36 + 1;
  const Scalar _tmp38 = _qic[3] * _tmp24;
  const Scalar _tmp39 = 2 * _qic[0] * _qic[2];
  const Scalar _tmp40 = _tmp38 + _tmp39;
  const Scalar _tmp41 = -_tmp28;
  const Scalar _tmp42 = _tmp29 + _tmp41;
  const Scalar _tmp43 = _tmp20 * _tmp42 + _tmp27 * _tmp40 + _tmp31 * _tmp4 + tic(0, 0);
  const Scalar _tmp44 = _Qi[3] * _tmp10;
  const Scalar _tmp45 = _Qi[0] * _tmp12;
  const Scalar _tmp46 = _tmp44 + _tmp45;
  const Scalar _tmp47 = _tmp17 + _tmp3;
  const Scalar _tmp48 = -_tmp38;
  const Scalar _tmp49 = _tmp39 + _tmp48;
  const Scalar _tmp50 = _tmp22 + _tmp25;
  const Scalar _tmp51 = _tmp20 * _tmp50 + _tmp27 * _tmp47 + _tmp31 * _tmp49 + tic(2, 0);
  const Scalar _tmp52 = Pi(0, 0) - Pj(0, 0) + _tmp15 * _tmp32 + _tmp37 * _tmp43 + _tmp46 * _tmp51;
  const Scalar _tmp53 = 2 * _Qj[1];
  const Scalar _tmp54 = _Qj[3] * _tmp53;
  const Scalar _tmp55 = -_tmp54;
  const Scalar _tmp56 = 2 * _Qj[0] * _Qj[2];
  const Scalar _tmp57 = _tmp55 + _tmp56;
  const Scalar _tmp58 = -_tmp44;
  const Scalar _tmp59 = _tmp45 + _tmp58;
  const Scalar _tmp60 = _Qi[1] * _tmp12;
  const Scalar _tmp61 = 2 * _Qi[0] * _Qi[3];
  const Scalar _tmp62 = _tmp60 + _tmp61;
  const Scalar _tmp63 = std::pow(_Qi[0], Scalar(2));
  const Scalar _tmp64 = 1 - 2 * _tmp63;
  const Scalar _tmp65 = _tmp36 + _tmp64;
  const Scalar _tmp66 = Pi(2, 0) - Pj(2, 0) + _tmp32 * _tmp62 + _tmp43 * _tmp59 + _tmp51 * _tmp65;
  const Scalar _tmp67 = 2 * _Qj[3];
  const Scalar _tmp68 = _Qj[2] * _tmp67;
  const Scalar _tmp69 = _Qj[0] * _tmp53;
  const Scalar _tmp70 = _tmp68 + _tmp69;
  const Scalar _tmp71 = _tmp11 + _tmp13;
  const Scalar _tmp72 = _tmp34 + _tmp64;
  const Scalar _tmp73 = -_tmp61;
  const Scalar _tmp74 = _tmp60 + _tmp73;
  const Scalar _tmp75 = Pi(1, 0) - Pj(1, 0) + _tmp32 * _tmp72 + _tmp43 * _tmp71 + _tmp51 * _tmp74;
  const Scalar _tmp76 = _tmp57 * _tmp66 + _tmp70 * _tmp75;
  const Scalar _tmp77 = _tmp52 * _tmp9 + _tmp76 - tic(0, 0);
  const Scalar _tmp78 = std::pow(_Qj[0], Scalar(2));
  const Scalar _tmp79 = 1 - 2 * _tmp78;
  const Scalar _tmp80 = _tmp6 + _tmp79;
  const Scalar _tmp81 = _Qj[2] * _tmp53;
  const Scalar _tmp82 = _Qj[0] * _tmp67;
  const Scalar _tmp83 = -_tmp82;
  const Scalar _tmp84 = _tmp81 + _tmp83;
  const Scalar _tmp85 = _tmp54 + _tmp56;
  const Scalar _tmp86 = _tmp52 * _tmp85 + _tmp75 * _tmp84;
  const Scalar _tmp87 = _tmp66 * _tmp80 + _tmp86 - tic(2, 0);
  const Scalar _tmp88 = _tmp79 + _tmp8;
  const Scalar _tmp89 = _tmp81 + _tmp82;
  const Scalar _tmp90 = -_tmp68;
  const Scalar _tmp91 = _tmp69 + _tmp90;
  const Scalar _tmp92 = _tmp52 * _tmp91 + _tmp66 * _tmp89;
  const Scalar _tmp93 = _tmp75 * _tmp88 + _tmp92 - tic(1, 0);
  const Scalar _tmp94 = _tmp30 * _tmp93 + _tmp49 * _tmp87;
  const Scalar _tmp95 = _tmp4 * _tmp77 + _tmp94;
  const Scalar _tmp96 = _tmp26 * _tmp93 + _tmp40 * _tmp77;
  const Scalar _tmp97 = _tmp47 * _tmp87 + _tmp96;
  const Scalar _tmp98 = Scalar(1.0) / (_tmp97);
  const Scalar _tmp99 = _tmp95 * _tmp98 - pts_j(0, 0);
  const Scalar _tmp100 = Scalar(306.66666666666703) * _tmp99;
  const Scalar _tmp101 = _tmp42 * _tmp77 + _tmp50 * _tmp87;
  const Scalar _tmp102 = _tmp101 + _tmp18 * _tmp93;
  const Scalar _tmp103 = _tmp102 * _tmp98 - pts_j(1, 0);
  const Scalar _tmp104 = Scalar(306.66666666666703) * _tmp103;
  const Scalar _tmp105 = _tmp40 * _tmp9;
  const Scalar _tmp106 = _tmp47 * _tmp85;
  const Scalar _tmp107 = _tmp26 * _tmp91;
  const Scalar _tmp108 = _tmp105 + _tmp106 + _tmp107;
  const Scalar _tmp109 = std::pow(_tmp97, Scalar(-2));
  const Scalar _tmp110 = _tmp109 * _tmp95;
  const Scalar _tmp111 = _tmp4 * _tmp9;
  const Scalar _tmp112 = _tmp49 * _tmp85;
  const Scalar _tmp113 = _tmp30 * _tmp91;
  const Scalar _tmp114 = -_tmp108 * _tmp110 + _tmp98 * (_tmp111 + _tmp112 + _tmp113);
  const Scalar _tmp115 = Scalar(306.66666666666703) * _tmp114;
  const Scalar _tmp116 = _tmp102 * _tmp109;
  const Scalar _tmp117 = _tmp18 * _tmp91;
  const Scalar _tmp118 = _tmp50 * _tmp85;
  const Scalar _tmp119 = _tmp42 * _tmp9;
  const Scalar _tmp120 = -_tmp108 * _tmp116 + _tmp98 * (_tmp117 + _tmp118 + _tmp119);
  const Scalar _tmp121 = _tmp40 * _tmp70;
  const Scalar _tmp122 = _tmp47 * _tmp84;
  const Scalar _tmp123 = _tmp26 * _tmp88;
  const Scalar _tmp124 = _tmp121 + _tmp122 + _tmp123;
  const Scalar _tmp125 = _tmp49 * _tmp84;
  const Scalar _tmp126 = _tmp4 * _tmp70;
  const Scalar _tmp127 = _tmp30 * _tmp88;
  const Scalar _tmp128 = -_tmp110 * _tmp124 + _tmp98 * (_tmp125 + _tmp126 + _tmp127);
  const Scalar _tmp129 = Scalar(306.66666666666703) * _tmp128;
  const Scalar _tmp130 = _tmp18 * _tmp88;
  const Scalar _tmp131 = _tmp50 * _tmp84;
  const Scalar _tmp132 = _tmp42 * _tmp70;
  const Scalar _tmp133 = -_tmp116 * _tmp124 + _tmp98 * (_tmp130 + _tmp131 + _tmp132);
  const Scalar _tmp134 = Scalar(306.66666666666703) * _tmp133;
  const Scalar _tmp135 = _tmp47 * _tmp80;
  const Scalar _tmp136 = _tmp40 * _tmp57;
  const Scalar _tmp137 = _tmp26 * _tmp89;
  const Scalar _tmp138 = _tmp135 + _tmp136 + _tmp137;
  const Scalar _tmp139 = _tmp49 * _tmp80;
  const Scalar _tmp140 = _tmp4 * _tmp57;
  const Scalar _tmp141 = _tmp30 * _tmp89;
  const Scalar _tmp142 = -_tmp110 * _tmp138 + _tmp98 * (_tmp139 + _tmp140 + _tmp141);
  const Scalar _tmp143 = Scalar(306.66666666666703) * _tmp142;
  const Scalar _tmp144 = _tmp18 * _tmp89;
  const Scalar _tmp145 = _tmp50 * _tmp80;
  const Scalar _tmp146 = _tmp42 * _tmp57;
  const Scalar _tmp147 = -_tmp116 * _tmp138 + _tmp98 * (_tmp144 + _tmp145 + _tmp146);
  const Scalar _tmp148 = Scalar(306.66666666666703) * _tmp147;
  const Scalar _tmp149 = std::pow(_Qi[3], Scalar(2));
  const Scalar _tmp150 = -_tmp35;
  const Scalar _tmp151 = _tmp149 + _tmp150;
  const Scalar _tmp152 = -_tmp63;
  const Scalar _tmp153 = _tmp152 + _tmp33;
  const Scalar _tmp154 = -_tmp60;
  const Scalar _tmp155 = _tmp32 * (_tmp151 + _tmp153) + _tmp51 * (_tmp154 + _tmp73);
  const Scalar _tmp156 = -_tmp149;
  const Scalar _tmp157 = _tmp32 * _tmp74 + _tmp51 * (_tmp150 + _tmp156 + _tmp33 + _tmp63);
  const Scalar _tmp158 = -_tmp11;
  const Scalar _tmp159 = _tmp32 * _tmp46 + _tmp51 * (_tmp13 + _tmp158);
  const Scalar _tmp160 = _tmp155 * _tmp89 + _tmp157 * _tmp88 + _tmp159 * _tmp91;
  const Scalar _tmp161 = _tmp155 * _tmp80 + _tmp157 * _tmp84 + _tmp159 * _tmp85;
  const Scalar _tmp162 = _tmp155 * _tmp57 + _tmp157 * _tmp70 + _tmp159 * _tmp9;
  const Scalar _tmp163 = _tmp160 * _tmp26 + _tmp161 * _tmp47 + _tmp162 * _tmp40;
  const Scalar _tmp164 =
      -_tmp110 * _tmp163 + _tmp98 * (_tmp160 * _tmp30 + _tmp161 * _tmp49 + _tmp162 * _tmp4);
  const Scalar _tmp165 = Scalar(306.66666666666703) * _tmp164;
  const Scalar _tmp166 =
      -_tmp116 * _tmp163 + _tmp98 * (_tmp160 * _tmp18 + _tmp161 * _tmp50 + _tmp162 * _tmp42);
  const Scalar _tmp167 = Scalar(306.66666666666703) * _tmp166;
  const Scalar _tmp168 = -_tmp33;
  const Scalar _tmp169 = _tmp168 + _tmp63;
  const Scalar _tmp170 = _tmp156 + _tmp35;
  const Scalar _tmp171 = _tmp43 * (_tmp169 + _tmp170) + _tmp51 * _tmp59;
  const Scalar _tmp172 = _tmp43 * (_tmp154 + _tmp61) + _tmp51 * _tmp71;
  const Scalar _tmp173 = -_tmp45;
  const Scalar _tmp174 = _tmp43 * (_tmp173 + _tmp58) + _tmp51 * (_tmp151 + _tmp169);
  const Scalar _tmp175 = _tmp171 * _tmp89 + _tmp172 * _tmp88 + _tmp174 * _tmp91;
  const Scalar _tmp176 = _tmp171 * _tmp57 + _tmp172 * _tmp70 + _tmp174 * _tmp9;
  const Scalar _tmp177 = _tmp171 * _tmp80 + _tmp172 * _tmp84 + _tmp174 * _tmp85;
  const Scalar _tmp178 = _tmp175 * _tmp26 + _tmp176 * _tmp40 + _tmp177 * _tmp47;
  const Scalar _tmp179 =
      -_tmp110 * _tmp178 + _tmp98 * (_tmp175 * _tmp30 + _tmp176 * _tmp4 + _tmp177 * _tmp49);
  const Scalar _tmp180 = Scalar(306.66666666666703) * _tmp179;
  const Scalar _tmp181 =
      -_tmp116 * _tmp178 + _tmp98 * (_tmp175 * _tmp18 + _tmp176 * _tmp42 + _tmp177 * _tmp50);
  const Scalar _tmp182 = _tmp15 * _tmp43 + _tmp32 * (_tmp153 + _tmp170);
  const Scalar _tmp183 =
      _tmp32 * (_tmp14 + _tmp158) + _tmp43 * (_tmp149 + _tmp152 + _tmp168 + _tmp35);
  const Scalar _tmp184 = _tmp32 * (_tmp173 + _tmp44) + _tmp43 * _tmp62;
  const Scalar _tmp185 = _tmp182 * _tmp91 + _tmp183 * _tmp88 + _tmp184 * _tmp89;
  const Scalar _tmp186 = _tmp182 * _tmp85 + _tmp183 * _tmp84 + _tmp184 * _tmp80;
  const Scalar _tmp187 = _tmp182 * _tmp9 + _tmp183 * _tmp70 + _tmp184 * _tmp57;
  const Scalar _tmp188 = _tmp185 * _tmp26 + _tmp186 * _tmp47 + _tmp187 * _tmp40;
  const Scalar _tmp189 =
      -_tmp110 * _tmp188 + _tmp98 * (_tmp185 * _tmp30 + _tmp186 * _tmp49 + _tmp187 * _tmp4);
  const Scalar _tmp190 =
      -_tmp116 * _tmp188 + _tmp98 * (_tmp18 * _tmp185 + _tmp186 * _tmp50 + _tmp187 * _tmp42);
  const Scalar _tmp191 = -_tmp105 - _tmp106 - _tmp107;
  const Scalar _tmp192 = -_tmp110 * _tmp191 + _tmp98 * (-_tmp111 - _tmp112 - _tmp113);
  const Scalar _tmp193 = Scalar(306.66666666666703) * _tmp192;
  const Scalar _tmp194 = -_tmp116 * _tmp191 + _tmp98 * (-_tmp117 - _tmp118 - _tmp119);
  const Scalar _tmp195 = -_tmp121 - _tmp122 - _tmp123;
  const Scalar _tmp196 = -_tmp110 * _tmp195 + _tmp98 * (-_tmp125 - _tmp126 - _tmp127);
  const Scalar _tmp197 = Scalar(306.66666666666703) * _tmp196;
  const Scalar _tmp198 = -_tmp116 * _tmp195 + _tmp98 * (-_tmp130 - _tmp131 - _tmp132);
  const Scalar _tmp199 = Scalar(306.66666666666703) * _tmp198;
  const Scalar _tmp200 = -_tmp135 - _tmp136 - _tmp137;
  const Scalar _tmp201 = -_tmp110 * _tmp200 + _tmp98 * (-_tmp139 - _tmp140 - _tmp141);
  const Scalar _tmp202 = Scalar(306.66666666666703) * _tmp201;
  const Scalar _tmp203 = -_tmp116 * _tmp200 + _tmp98 * (-_tmp144 - _tmp145 - _tmp146);
  const Scalar _tmp204 = Scalar(306.66666666666703) * _tmp203;
  const Scalar _tmp205 = -_tmp81;
  const Scalar _tmp206 = std::pow(_Qj[3], Scalar(2));
  const Scalar _tmp207 = -_tmp206;
  const Scalar _tmp208 = -_tmp5;
  const Scalar _tmp209 = -_tmp69;
  const Scalar _tmp210 = _tmp52 * (_tmp209 + _tmp68) + _tmp66 * (_tmp205 + _tmp83) +
                         _tmp75 * (_tmp207 + _tmp208 + _tmp7 + _tmp78);
  const Scalar _tmp211 = -_tmp78;
  const Scalar _tmp212 = _tmp211 + _tmp7;
  const Scalar _tmp213 = _tmp206 + _tmp208;
  const Scalar _tmp214 = _tmp66 * (_tmp212 + _tmp213) + _tmp86;
  const Scalar _tmp215 = _tmp210 * _tmp47 + _tmp214 * _tmp26;
  const Scalar _tmp216 = -_tmp110 * _tmp215 + _tmp98 * (_tmp210 * _tmp49 + _tmp214 * _tmp30);
  const Scalar _tmp217 = Scalar(306.66666666666703) * _tmp216;
  const Scalar _tmp218 = -_tmp116 * _tmp215 + _tmp98 * (_tmp18 * _tmp214 + _tmp210 * _tmp50);
  const Scalar _tmp219 = Scalar(306.66666666666703) * _tmp218;
  const Scalar _tmp220 = _tmp207 + _tmp5;
  const Scalar _tmp221 = -_tmp7;
  const Scalar _tmp222 = _tmp221 + _tmp78;
  const Scalar _tmp223 = -_tmp56;
  const Scalar _tmp224 =
      _tmp52 * (_tmp223 + _tmp55) + _tmp66 * (_tmp220 + _tmp222) + _tmp75 * (_tmp205 + _tmp82);
  const Scalar _tmp225 = _tmp52 * (_tmp213 + _tmp222) + _tmp76;
  const Scalar _tmp226 = _tmp224 * _tmp40 + _tmp225 * _tmp47;
  const Scalar _tmp227 = -_tmp110 * _tmp226 + _tmp98 * (_tmp224 * _tmp4 + _tmp225 * _tmp49);
  const Scalar _tmp228 = Scalar(306.66666666666703) * _tmp227;
  const Scalar _tmp229 = -_tmp116 * _tmp226 + _tmp98 * (_tmp224 * _tmp42 + _tmp225 * _tmp50);
  const Scalar _tmp230 = Scalar(306.66666666666703) * _tmp229;
  const Scalar _tmp231 = _tmp75 * (_tmp206 + _tmp211 + _tmp221 + _tmp5) + _tmp92;
  const Scalar _tmp232 =
      _tmp52 * (_tmp212 + _tmp220) + _tmp66 * (_tmp223 + _tmp54) + _tmp75 * (_tmp209 + _tmp90);
  const Scalar _tmp233 = _tmp231 * _tmp40 + _tmp232 * _tmp26;
  const Scalar _tmp234 = -_tmp110 * _tmp233 + _tmp98 * (_tmp231 * _tmp4 + _tmp232 * _tmp30);
  const Scalar _tmp235 = Scalar(306.66666666666703) * _tmp234;
  const Scalar _tmp236 = -_tmp116 * _tmp233 + _tmp98 * (_tmp18 * _tmp232 + _tmp231 * _tmp42);
  const Scalar _tmp237 = Scalar(306.66666666666703) * _tmp236;
  const Scalar _tmp238 = _tmp37 * _tmp85 + _tmp59 * _tmp80 + _tmp71 * _tmp84;
  const Scalar _tmp239 = _tmp37 * _tmp91 + _tmp59 * _tmp89 + _tmp71 * _tmp88;
  const Scalar _tmp240 = _tmp37 * _tmp9 + _tmp57 * _tmp59 + _tmp70 * _tmp71 - 1;
  const Scalar _tmp241 = _tmp238 * _tmp47 + _tmp239 * _tmp26 + _tmp240 * _tmp40;
  const Scalar _tmp242 =
      -_tmp110 * _tmp241 + _tmp98 * (_tmp238 * _tmp49 + _tmp239 * _tmp30 + _tmp240 * _tmp4);
  const Scalar _tmp243 = Scalar(306.66666666666703) * _tmp242;
  const Scalar _tmp244 =
      -_tmp116 * _tmp241 + _tmp98 * (_tmp18 * _tmp239 + _tmp238 * _tmp50 + _tmp240 * _tmp42);
  const Scalar _tmp245 = _tmp15 * _tmp85 + _tmp62 * _tmp80 + _tmp72 * _tmp84;
  const Scalar _tmp246 = _tmp15 * _tmp9 + _tmp57 * _tmp62 + _tmp70 * _tmp72;
  const Scalar _tmp247 = _tmp15 * _tmp91 + _tmp62 * _tmp89 + _tmp72 * _tmp88 - 1;
  const Scalar _tmp248 = _tmp245 * _tmp47 + _tmp246 * _tmp40 + _tmp247 * _tmp26;
  const Scalar _tmp249 =
      -_tmp110 * _tmp248 + _tmp98 * (_tmp245 * _tmp49 + _tmp246 * _tmp4 + _tmp247 * _tmp30);
  const Scalar _tmp250 = Scalar(306.66666666666703) * _tmp249;
  const Scalar _tmp251 =
      -_tmp116 * _tmp248 + _tmp98 * (_tmp18 * _tmp247 + _tmp245 * _tmp50 + _tmp246 * _tmp42);
  const Scalar _tmp252 = Scalar(306.66666666666703) * _tmp251;
  const Scalar _tmp253 = _tmp46 * _tmp9 + _tmp57 * _tmp65 + _tmp70 * _tmp74;
  const Scalar _tmp254 = _tmp46 * _tmp91 + _tmp65 * _tmp89 + _tmp74 * _tmp88;
  const Scalar _tmp255 = _tmp46 * _tmp85 + _tmp65 * _tmp80 + _tmp74 * _tmp84 - 1;
  const Scalar _tmp256 = _tmp253 * _tmp40 + _tmp254 * _tmp26 + _tmp255 * _tmp47;
  const Scalar _tmp257 =
      -_tmp110 * _tmp256 + _tmp98 * (_tmp253 * _tmp4 + _tmp254 * _tmp30 + _tmp255 * _tmp49);
  const Scalar _tmp258 =
      -_tmp116 * _tmp256 + _tmp98 * (_tmp18 * _tmp254 + _tmp253 * _tmp42 + _tmp255 * _tmp50);
  const Scalar _tmp259 = -_tmp25;
  const Scalar _tmp260 = _tmp23 + _tmp259;
  const Scalar _tmp261 = -_tmp2;
  const Scalar _tmp262 = _tmp0 + _tmp261;
  const Scalar _tmp263 = std::pow(_qic[3], Scalar(2));
  const Scalar _tmp264 = -_tmp263;
  const Scalar _tmp265 = _tmp16 + _tmp264;
  const Scalar _tmp266 = _tmp262 + _tmp265;
  const Scalar _tmp267 = _tmp20 * _tmp26 + _tmp266 * _tmp27;
  const Scalar _tmp268 = -_tmp16;
  const Scalar _tmp269 = _tmp263 + _tmp268;
  const Scalar _tmp270 = _tmp262 + _tmp269;
  const Scalar _tmp271 = _tmp20 * _tmp270 + _tmp260 * _tmp27;
  const Scalar _tmp272 = -_tmp29;
  const Scalar _tmp273 = _tmp272 + _tmp28;
  const Scalar _tmp274 = _tmp20 * _tmp40 + _tmp27 * _tmp273;
  const Scalar _tmp275 = _tmp267 * _tmp72 + _tmp271 * _tmp74 + _tmp274 * _tmp71;
  const Scalar _tmp276 = _tmp267 * _tmp62 + _tmp271 * _tmp65 + _tmp274 * _tmp59;
  const Scalar _tmp277 = _tmp15 * _tmp267 + _tmp271 * _tmp46 + _tmp274 * _tmp37;
  const Scalar _tmp278 = _tmp275 * _tmp88 + _tmp276 * _tmp89 + _tmp277 * _tmp91;
  const Scalar _tmp279 = _tmp275 * _tmp84 + _tmp276 * _tmp80 + _tmp277 * _tmp85;
  const Scalar _tmp280 = _tmp275 * _tmp70 + _tmp276 * _tmp57 + _tmp277 * _tmp9;
  const Scalar _tmp281 = _tmp26 * _tmp278 + _tmp260 * _tmp87 + _tmp266 * _tmp93 + _tmp273 * _tmp77 +
                         _tmp279 * _tmp47 + _tmp280 * _tmp40;
  const Scalar _tmp282 =
      -_tmp110 * _tmp281 + _tmp98 * (_tmp278 * _tmp30 + _tmp279 * _tmp49 + _tmp280 * _tmp4);
  const Scalar _tmp283 =
      -_tmp116 * _tmp281 +
      _tmp98 * (_tmp18 * _tmp278 + _tmp270 * _tmp87 + _tmp279 * _tmp50 + _tmp280 * _tmp42 + _tmp96);
  const Scalar _tmp284 = -_tmp0;
  const Scalar _tmp285 = _tmp2 + _tmp284;
  const Scalar _tmp286 = _tmp265 + _tmp285;
  const Scalar _tmp287 = _tmp27 * _tmp49 + _tmp286 * _tmp31;
  const Scalar _tmp288 = _tmp16 + _tmp261 + _tmp263 + _tmp284;
  const Scalar _tmp289 = -_tmp39;
  const Scalar _tmp290 = _tmp289 + _tmp48;
  const Scalar _tmp291 = _tmp27 * _tmp288 + _tmp290 * _tmp31;
  const Scalar _tmp292 = _tmp22 + _tmp259;
  const Scalar _tmp293 = _tmp27 * _tmp30 + _tmp292 * _tmp31;
  const Scalar _tmp294 = _tmp287 * _tmp65 + _tmp291 * _tmp59 + _tmp293 * _tmp62;
  const Scalar _tmp295 = _tmp15 * _tmp293 + _tmp287 * _tmp46 + _tmp291 * _tmp37;
  const Scalar _tmp296 = _tmp287 * _tmp74 + _tmp291 * _tmp71 + _tmp293 * _tmp72;
  const Scalar _tmp297 = _tmp294 * _tmp57 + _tmp295 * _tmp9 + _tmp296 * _tmp70;
  const Scalar _tmp298 = _tmp294 * _tmp80 + _tmp295 * _tmp85 + _tmp296 * _tmp84;
  const Scalar _tmp299 = _tmp294 * _tmp89 + _tmp295 * _tmp91 + _tmp296 * _tmp88;
  const Scalar _tmp300 =
      _tmp26 * _tmp299 + _tmp288 * _tmp77 + _tmp297 * _tmp40 + _tmp298 * _tmp47 + _tmp94;
  const Scalar _tmp301 =
      -_tmp110 * _tmp300 + _tmp98 * (_tmp286 * _tmp87 + _tmp290 * _tmp77 + _tmp292 * _tmp93 +
                                     _tmp297 * _tmp4 + _tmp298 * _tmp49 + _tmp299 * _tmp30);
  const Scalar _tmp302 = Scalar(306.66666666666703) * _tmp301;
  const Scalar _tmp303 =
      -_tmp116 * _tmp300 + _tmp98 * (_tmp18 * _tmp299 + _tmp297 * _tmp42 + _tmp298 * _tmp50);
  const Scalar _tmp304 = _tmp289 + _tmp38;
  const Scalar _tmp305 = _tmp20 * _tmp304 + _tmp31 * _tmp50;
  const Scalar _tmp306 = _tmp0 + _tmp2 + _tmp264 + _tmp268;
  const Scalar _tmp307 = _tmp20 * _tmp306 + _tmp31 * _tmp42;
  const Scalar _tmp308 = _tmp269 + _tmp285;
  const Scalar _tmp309 = _tmp272 + _tmp41;
  const Scalar _tmp310 = _tmp20 * _tmp309 + _tmp308 * _tmp31;
  const Scalar _tmp311 = _tmp305 * _tmp74 + _tmp307 * _tmp71 + _tmp310 * _tmp72;
  const Scalar _tmp312 = _tmp15 * _tmp310 + _tmp305 * _tmp46 + _tmp307 * _tmp37;
  const Scalar _tmp313 = _tmp305 * _tmp65 + _tmp307 * _tmp59 + _tmp310 * _tmp62;
  const Scalar _tmp314 = _tmp311 * _tmp70 + _tmp312 * _tmp9 + _tmp313 * _tmp57;
  const Scalar _tmp315 = _tmp311 * _tmp84 + _tmp312 * _tmp85 + _tmp313 * _tmp80;
  const Scalar _tmp316 = _tmp311 * _tmp88 + _tmp312 * _tmp91 + _tmp313 * _tmp89;
  const Scalar _tmp317 = _tmp26 * _tmp316 + _tmp314 * _tmp40 + _tmp315 * _tmp47;
  const Scalar _tmp318 =
      -_tmp110 * _tmp317 +
      _tmp98 * (_tmp101 + _tmp30 * _tmp316 + _tmp308 * _tmp93 + _tmp314 * _tmp4 + _tmp315 * _tmp49);
  const Scalar _tmp319 =
      -_tmp116 * _tmp317 + _tmp98 * (_tmp18 * _tmp316 + _tmp304 * _tmp87 + _tmp306 * _tmp77 +
                                     _tmp309 * _tmp93 + _tmp314 * _tmp42 + _tmp315 * _tmp50);
  const Scalar _tmp320 = Scalar(306.66666666666703) * _tmp319;
  const Scalar _tmp321 = std::pow(inv_dep_i, Scalar(-2));
  const Scalar _tmp322 = _tmp321 * pts_i(0, 0);
  const Scalar _tmp323 = _tmp321 * pts_i(2, 0);
  const Scalar _tmp324 = _tmp321 * pts_i(1, 0);
  const Scalar _tmp325 = -_tmp322 * _tmp4 - _tmp323 * _tmp40 - _tmp324 * _tmp42;
  const Scalar _tmp326 = -_tmp18 * _tmp324 - _tmp26 * _tmp323 - _tmp30 * _tmp322;
  const Scalar _tmp327 = -_tmp322 * _tmp49 - _tmp323 * _tmp47 - _tmp324 * _tmp50;
  const Scalar _tmp328 = _tmp15 * _tmp326 + _tmp325 * _tmp37 + _tmp327 * _tmp46;
  const Scalar _tmp329 = _tmp325 * _tmp71 + _tmp326 * _tmp72 + _tmp327 * _tmp74;
  const Scalar _tmp330 = _tmp325 * _tmp59 + _tmp326 * _tmp62 + _tmp327 * _tmp65;
  const Scalar _tmp331 = _tmp328 * _tmp9 + _tmp329 * _tmp70 + _tmp330 * _tmp57;
  const Scalar _tmp332 = _tmp328 * _tmp85 + _tmp329 * _tmp84 + _tmp330 * _tmp80;
  const Scalar _tmp333 = _tmp328 * _tmp91 + _tmp329 * _tmp88 + _tmp330 * _tmp89;
  const Scalar _tmp334 = _tmp26 * _tmp333 + _tmp331 * _tmp40 + _tmp332 * _tmp47;
  const Scalar _tmp335 =
      -_tmp110 * _tmp334 + _tmp98 * (_tmp30 * _tmp333 + _tmp331 * _tmp4 + _tmp332 * _tmp49);
  const Scalar _tmp336 = Scalar(306.66666666666703) * _tmp335;
  const Scalar _tmp337 =
      -_tmp116 * _tmp334 + _tmp98 * (_tmp18 * _tmp333 + _tmp331 * _tmp42 + _tmp332 * _tmp50);
  const Scalar _tmp338 = Scalar(94044.444444444671);
  const Scalar _tmp339 = _tmp128 * _tmp338;
  const Scalar _tmp340 = _tmp120 * _tmp338;
  const Scalar _tmp341 = _tmp147 * _tmp338;
  const Scalar _tmp342 = _tmp142 * _tmp338;
  const Scalar _tmp343 = _tmp164 * _tmp338;
  const Scalar _tmp344 = _tmp181 * _tmp338;
  const Scalar _tmp345 = _tmp114 * _tmp338;
  const Scalar _tmp346 = _tmp189 * _tmp338;
  const Scalar _tmp347 = _tmp192 * _tmp338;
  const Scalar _tmp348 = _tmp196 * _tmp338;
  const Scalar _tmp349 = _tmp203 * _tmp338;
  const Scalar _tmp350 = _tmp201 * _tmp338;
  const Scalar _tmp351 = _tmp216 * _tmp338;
  const Scalar _tmp352 = _tmp227 * _tmp338;
  const Scalar _tmp353 = _tmp236 * _tmp338;
  const Scalar _tmp354 = _tmp234 * _tmp338;
  const Scalar _tmp355 = _tmp242 * _tmp338;
  const Scalar _tmp356 = _tmp249 * _tmp338;
  const Scalar _tmp357 = _tmp257 * _tmp338;
  const Scalar _tmp358 = _tmp282 * _tmp338;
  const Scalar _tmp359 = _tmp303 * _tmp338;
  const Scalar _tmp360 = _tmp301 * _tmp338;
  const Scalar _tmp361 = _tmp335 * _tmp338;
  const Scalar _tmp362 = _tmp166 * _tmp338;
  const Scalar _tmp363 = _tmp190 * _tmp338;
  const Scalar _tmp364 = _tmp194 * _tmp338;
  const Scalar _tmp365 = _tmp198 * _tmp338;
  const Scalar _tmp366 = _tmp133 * _tmp338;
  const Scalar _tmp367 = _tmp319 * _tmp338;
  const Scalar _tmp368 = _tmp218 * _tmp338;
  const Scalar _tmp369 = _tmp258 * _tmp338;
  const Scalar _tmp370 = _tmp337 * _tmp338;
  const Scalar _tmp371 = _tmp244 * _tmp338;
  const Scalar _tmp372 = _tmp229 * _tmp338;

  // Output terms (4)
  if (res != nullptr) {
    Eigen::Matrix<Scalar, 2, 1>& _res = (*res);

    _res(0, 0) = _tmp100;
    _res(1, 0) = _tmp104;
  }

  if (jacobian != nullptr) {
    Eigen::Matrix<Scalar, 2, 19>& _jacobian = (*jacobian);

    _jacobian(0, 0) = _tmp115;
    _jacobian(1, 0) = Scalar(306.66666666666703) * _tmp120;
    _jacobian(0, 1) = _tmp129;
    _jacobian(1, 1) = _tmp134;
    _jacobian(0, 2) = _tmp143;
    _jacobian(1, 2) = _tmp148;
    _jacobian(0, 3) = _tmp165;
    _jacobian(1, 3) = _tmp167;
    _jacobian(0, 4) = _tmp180;
    _jacobian(1, 4) = Scalar(306.66666666666703) * _tmp181;
    _jacobian(0, 5) = Scalar(306.66666666666703) * _tmp189;
    _jacobian(1, 5) = Scalar(306.66666666666703) * _tmp190;
    _jacobian(0, 6) = _tmp193;
    _jacobian(1, 6) = Scalar(306.66666666666703) * _tmp194;
    _jacobian(0, 7) = _tmp197;
    _jacobian(1, 7) = _tmp199;
    _jacobian(0, 8) = _tmp202;
    _jacobian(1, 8) = _tmp204;
    _jacobian(0, 9) = _tmp217;
    _jacobian(1, 9) = _tmp219;
    _jacobian(0, 10) = _tmp228;
    _jacobian(1, 10) = _tmp230;
    _jacobian(0, 11) = _tmp235;
    _jacobian(1, 11) = _tmp237;
    _jacobian(0, 12) = _tmp243;
    _jacobian(1, 12) = Scalar(306.66666666666703) * _tmp244;
    _jacobian(0, 13) = _tmp250;
    _jacobian(1, 13) = _tmp252;
    _jacobian(0, 14) = Scalar(306.66666666666703) * _tmp257;
    _jacobian(1, 14) = Scalar(306.66666666666703) * _tmp258;
    _jacobian(0, 15) = Scalar(306.66666666666703) * _tmp282;
    _jacobian(1, 15) = Scalar(306.66666666666703) * _tmp283;
    _jacobian(0, 16) = _tmp302;
    _jacobian(1, 16) = Scalar(306.66666666666703) * _tmp303;
    _jacobian(0, 17) = Scalar(306.66666666666703) * _tmp318;
    _jacobian(1, 17) = _tmp320;
    _jacobian(0, 18) = _tmp336;
    _jacobian(1, 18) = Scalar(306.66666666666703) * _tmp337;
  }

  if (hessian != nullptr) {
    Eigen::Matrix<Scalar, 19, 19>& _hessian = (*hessian);

    _hessian(0, 0) =
        std::pow(_tmp114, Scalar(2)) * _tmp338 + std::pow(_tmp120, Scalar(2)) * _tmp338;
    _hessian(1, 0) = _tmp114 * _tmp339 + _tmp133 * _tmp340;
    _hessian(2, 0) = _tmp114 * _tmp342 + _tmp120 * _tmp341;
    _hessian(3, 0) = _tmp114 * _tmp343 + _tmp166 * _tmp340;
    _hessian(4, 0) = _tmp120 * _tmp344 + _tmp179 * _tmp345;
    _hessian(5, 0) = _tmp114 * _tmp346 + _tmp190 * _tmp340;
    _hessian(6, 0) = _tmp114 * _tmp347 + _tmp194 * _tmp340;
    _hessian(7, 0) = _tmp114 * _tmp348 + _tmp198 * _tmp340;
    _hessian(8, 0) = _tmp114 * _tmp350 + _tmp120 * _tmp349;
    _hessian(9, 0) = _tmp114 * _tmp351 + _tmp218 * _tmp340;
    _hessian(10, 0) = _tmp114 * _tmp352 + _tmp229 * _tmp340;
    _hessian(11, 0) = _tmp114 * _tmp354 + _tmp120 * _tmp353;
    _hessian(12, 0) = _tmp114 * _tmp355 + _tmp244 * _tmp340;
    _hessian(13, 0) = _tmp114 * _tmp356 + _tmp251 * _tmp340;
    _hessian(14, 0) = _tmp114 * _tmp357 + _tmp258 * _tmp340;
    _hessian(15, 0) = _tmp114 * _tmp358 + _tmp283 * _tmp340;
    _hessian(16, 0) = _tmp114 * _tmp360 + _tmp120 * _tmp359;
    _hessian(17, 0) = _tmp318 * _tmp345 + _tmp319 * _tmp340;
    _hessian(18, 0) = _tmp114 * _tmp361 + _tmp337 * _tmp340;
    _hessian(0, 1) = 0;
    _hessian(1, 1) =
        std::pow(_tmp128, Scalar(2)) * _tmp338 + std::pow(_tmp133, Scalar(2)) * _tmp338;
    _hessian(2, 1) = _tmp128 * _tmp342 + _tmp133 * _tmp341;
    _hessian(3, 1) = _tmp128 * _tmp343 + _tmp133 * _tmp362;
    _hessian(4, 1) = _tmp133 * _tmp344 + _tmp179 * _tmp339;
    _hessian(5, 1) = _tmp128 * _tmp346 + _tmp133 * _tmp363;
    _hessian(6, 1) = _tmp128 * _tmp347 + _tmp133 * _tmp364;
    _hessian(7, 1) = _tmp133 * _tmp365 + _tmp196 * _tmp339;
    _hessian(8, 1) = _tmp128 * _tmp350 + _tmp133 * _tmp349;
    _hessian(9, 1) = _tmp128 * _tmp351 + _tmp218 * _tmp366;
    _hessian(10, 1) = _tmp128 * _tmp352 + _tmp229 * _tmp366;
    _hessian(11, 1) = _tmp128 * _tmp354 + _tmp133 * _tmp353;
    _hessian(12, 1) = _tmp128 * _tmp355 + _tmp244 * _tmp366;
    _hessian(13, 1) = _tmp128 * _tmp356 + _tmp251 * _tmp366;
    _hessian(14, 1) = _tmp128 * _tmp357 + _tmp258 * _tmp366;
    _hessian(15, 1) = _tmp128 * _tmp358 + _tmp283 * _tmp366;
    _hessian(16, 1) = _tmp133 * _tmp359 + _tmp301 * _tmp339;
    _hessian(17, 1) = _tmp133 * _tmp367 + _tmp318 * _tmp339;
    _hessian(18, 1) = _tmp128 * _tmp361 + _tmp337 * _tmp366;
    _hessian(0, 2) = 0;
    _hessian(1, 2) = 0;
    _hessian(2, 2) =
        std::pow(_tmp142, Scalar(2)) * _tmp338 + std::pow(_tmp147, Scalar(2)) * _tmp338;
    _hessian(3, 2) = _tmp142 * _tmp343 + _tmp166 * _tmp341;
    _hessian(4, 2) = _tmp179 * _tmp342 + _tmp181 * _tmp341;
    _hessian(5, 2) = _tmp142 * _tmp346 + _tmp190 * _tmp341;
    _hessian(6, 2) = _tmp192 * _tmp342 + _tmp194 * _tmp341;
    _hessian(7, 2) = _tmp196 * _tmp342 + _tmp198 * _tmp341;
    _hessian(8, 2) = _tmp142 * _tmp350 + _tmp147 * _tmp349;
    _hessian(9, 2) = _tmp216 * _tmp342 + _tmp218 * _tmp341;
    _hessian(10, 2) = _tmp142 * _tmp352 + _tmp229 * _tmp341;
    _hessian(11, 2) = _tmp142 * _tmp354 + _tmp236 * _tmp341;
    _hessian(12, 2) = _tmp142 * _tmp355 + _tmp244 * _tmp341;
    _hessian(13, 2) = _tmp249 * _tmp342 + _tmp251 * _tmp341;
    _hessian(14, 2) = _tmp257 * _tmp342 + _tmp258 * _tmp341;
    _hessian(15, 2) = _tmp282 * _tmp342 + _tmp283 * _tmp341;
    _hessian(16, 2) = _tmp147 * _tmp359 + _tmp301 * _tmp342;
    _hessian(17, 2) = _tmp318 * _tmp342 + _tmp319 * _tmp341;
    _hessian(18, 2) = _tmp142 * _tmp361 + _tmp337 * _tmp341;
    _hessian(0, 3) = 0;
    _hessian(1, 3) = 0;
    _hessian(2, 3) = 0;
    _hessian(3, 3) =
        std::pow(_tmp164, Scalar(2)) * _tmp338 + std::pow(_tmp166, Scalar(2)) * _tmp338;
    _hessian(4, 3) = _tmp166 * _tmp344 + _tmp179 * _tmp343;
    _hessian(5, 3) = _tmp166 * _tmp363 + _tmp189 * _tmp343;
    _hessian(6, 3) = _tmp166 * _tmp364 + _tmp192 * _tmp343;
    _hessian(7, 3) = _tmp196 * _tmp343 + _tmp198 * _tmp362;
    _hessian(8, 3) = _tmp166 * _tmp349 + _tmp201 * _tmp343;
    _hessian(9, 3) = _tmp216 * _tmp343 + _tmp218 * _tmp362;
    _hessian(10, 3) = _tmp227 * _tmp343 + _tmp229 * _tmp362;
    _hessian(11, 3) = _tmp166 * _tmp353 + _tmp234 * _tmp343;
    _hessian(12, 3) = _tmp242 * _tmp343 + _tmp244 * _tmp362;
    _hessian(13, 3) = _tmp249 * _tmp343 + _tmp251 * _tmp362;
    _hessian(14, 3) = _tmp257 * _tmp343 + _tmp258 * _tmp362;
    _hessian(15, 3) = _tmp282 * _tmp343 + _tmp283 * _tmp362;
    _hessian(16, 3) = _tmp166 * _tmp359 + _tmp301 * _tmp343;
    _hessian(17, 3) = _tmp166 * _tmp367 + _tmp318 * _tmp343;
    _hessian(18, 3) = _tmp335 * _tmp343 + _tmp337 * _tmp362;
    _hessian(0, 4) = 0;
    _hessian(1, 4) = 0;
    _hessian(2, 4) = 0;
    _hessian(3, 4) = 0;
    _hessian(4, 4) =
        std::pow(_tmp179, Scalar(2)) * _tmp338 + std::pow(_tmp181, Scalar(2)) * _tmp338;
    _hessian(5, 4) = _tmp179 * _tmp346 + _tmp190 * _tmp344;
    _hessian(6, 4) = _tmp179 * _tmp347 + _tmp194 * _tmp344;
    _hessian(7, 4) = _tmp179 * _tmp348 + _tmp198 * _tmp344;
    _hessian(8, 4) = _tmp179 * _tmp350 + _tmp181 * _tmp349;
    _hessian(9, 4) = _tmp179 * _tmp351 + _tmp218 * _tmp344;
    _hessian(10, 4) = _tmp179 * _tmp352 + _tmp229 * _tmp344;
    _hessian(11, 4) = _tmp179 * _tmp354 + _tmp236 * _tmp344;
    _hessian(12, 4) = _tmp179 * _tmp355 + _tmp244 * _tmp344;
    _hessian(13, 4) = _tmp179 * _tmp356 + _tmp251 * _tmp344;
    _hessian(14, 4) = _tmp179 * _tmp357 + _tmp258 * _tmp344;
    _hessian(15, 4) = _tmp179 * _tmp358 + _tmp283 * _tmp344;
    _hessian(16, 4) = _tmp179 * _tmp360 + _tmp181 * _tmp359;
    _hessian(17, 4) = _tmp179 * _tmp318 * _tmp338 + _tmp319 * _tmp344;
    _hessian(18, 4) = _tmp179 * _tmp361 + _tmp337 * _tmp344;
    _hessian(0, 5) = 0;
    _hessian(1, 5) = 0;
    _hessian(2, 5) = 0;
    _hessian(3, 5) = 0;
    _hessian(4, 5) = 0;
    _hessian(5, 5) =
        std::pow(_tmp189, Scalar(2)) * _tmp338 + std::pow(_tmp190, Scalar(2)) * _tmp338;
    _hessian(6, 5) = _tmp190 * _tmp364 + _tmp192 * _tmp346;
    _hessian(7, 5) = _tmp196 * _tmp346 + _tmp198 * _tmp363;
    _hessian(8, 5) = _tmp189 * _tmp350 + _tmp190 * _tmp349;
    _hessian(9, 5) = _tmp216 * _tmp346 + _tmp218 * _tmp363;
    _hessian(10, 5) = _tmp189 * _tmp352 + _tmp229 * _tmp363;
    _hessian(11, 5) = _tmp189 * _tmp354 + _tmp190 * _tmp353;
    _hessian(12, 5) = _tmp189 * _tmp355 + _tmp244 * _tmp363;
    _hessian(13, 5) = _tmp249 * _tmp346 + _tmp251 * _tmp363;
    _hessian(14, 5) = _tmp257 * _tmp346 + _tmp258 * _tmp363;
    _hessian(15, 5) = _tmp282 * _tmp346 + _tmp283 * _tmp363;
    _hessian(16, 5) = _tmp190 * _tmp359 + _tmp301 * _tmp346;
    _hessian(17, 5) = _tmp190 * _tmp367 + _tmp318 * _tmp346;
    _hessian(18, 5) = _tmp335 * _tmp346 + _tmp337 * _tmp363;
    _hessian(0, 6) = 0;
    _hessian(1, 6) = 0;
    _hessian(2, 6) = 0;
    _hessian(3, 6) = 0;
    _hessian(4, 6) = 0;
    _hessian(5, 6) = 0;
    _hessian(6, 6) =
        std::pow(_tmp192, Scalar(2)) * _tmp338 + std::pow(_tmp194, Scalar(2)) * _tmp338;
    _hessian(7, 6) = _tmp196 * _tmp347 + _tmp198 * _tmp364;
    _hessian(8, 6) = _tmp192 * _tmp350 + _tmp194 * _tmp349;
    _hessian(9, 6) = _tmp192 * _tmp351 + _tmp218 * _tmp364;
    _hessian(10, 6) = _tmp192 * _tmp352 + _tmp229 * _tmp364;
    _hessian(11, 6) = _tmp192 * _tmp354 + _tmp194 * _tmp353;
    _hessian(12, 6) = _tmp192 * _tmp355 + _tmp244 * _tmp364;
    _hessian(13, 6) = _tmp192 * _tmp356 + _tmp251 * _tmp364;
    _hessian(14, 6) = _tmp257 * _tmp347 + _tmp258 * _tmp364;
    _hessian(15, 6) = _tmp192 * _tmp358 + _tmp283 * _tmp364;
    _hessian(16, 6) = _tmp194 * _tmp359 + _tmp301 * _tmp347;
    _hessian(17, 6) = _tmp318 * _tmp347 + _tmp319 * _tmp364;
    _hessian(18, 6) = _tmp192 * _tmp361 + _tmp337 * _tmp364;
    _hessian(0, 7) = 0;
    _hessian(1, 7) = 0;
    _hessian(2, 7) = 0;
    _hessian(3, 7) = 0;
    _hessian(4, 7) = 0;
    _hessian(5, 7) = 0;
    _hessian(6, 7) = 0;
    _hessian(7, 7) =
        std::pow(_tmp196, Scalar(2)) * _tmp338 + std::pow(_tmp198, Scalar(2)) * _tmp338;
    _hessian(8, 7) = _tmp196 * _tmp350 + _tmp198 * _tmp349;
    _hessian(9, 7) = _tmp196 * _tmp351 + _tmp218 * _tmp365;
    _hessian(10, 7) = _tmp196 * _tmp352 + _tmp229 * _tmp365;
    _hessian(11, 7) = _tmp196 * _tmp354 + _tmp198 * _tmp353;
    _hessian(12, 7) = _tmp196 * _tmp355 + _tmp244 * _tmp365;
    _hessian(13, 7) = _tmp196 * _tmp356 + _tmp251 * _tmp365;
    _hessian(14, 7) = _tmp196 * _tmp357 + _tmp258 * _tmp365;
    _hessian(15, 7) = _tmp196 * _tmp358 + _tmp283 * _tmp365;
    _hessian(16, 7) = _tmp196 * _tmp360 + _tmp198 * _tmp359;
    _hessian(17, 7) = _tmp198 * _tmp367 + _tmp318 * _tmp348;
    _hessian(18, 7) = _tmp196 * _tmp361 + _tmp337 * _tmp365;
    _hessian(0, 8) = 0;
    _hessian(1, 8) = 0;
    _hessian(2, 8) = 0;
    _hessian(3, 8) = 0;
    _hessian(4, 8) = 0;
    _hessian(5, 8) = 0;
    _hessian(6, 8) = 0;
    _hessian(7, 8) = 0;
    _hessian(8, 8) =
        std::pow(_tmp201, Scalar(2)) * _tmp338 + std::pow(_tmp203, Scalar(2)) * _tmp338;
    _hessian(9, 8) = _tmp216 * _tmp350 + _tmp218 * _tmp349;
    _hessian(10, 8) = _tmp227 * _tmp350 + _tmp229 * _tmp349;
    _hessian(11, 8) = _tmp234 * _tmp350 + _tmp236 * _tmp349;
    _hessian(12, 8) = _tmp201 * _tmp355 + _tmp244 * _tmp349;
    _hessian(13, 8) = _tmp249 * _tmp350 + _tmp251 * _tmp349;
    _hessian(14, 8) = _tmp257 * _tmp350 + _tmp258 * _tmp349;
    _hessian(15, 8) = _tmp282 * _tmp350 + _tmp283 * _tmp349;
    _hessian(16, 8) = _tmp203 * _tmp359 + _tmp301 * _tmp350;
    _hessian(17, 8) = _tmp318 * _tmp350 + _tmp319 * _tmp349;
    _hessian(18, 8) = _tmp335 * _tmp350 + _tmp337 * _tmp349;
    _hessian(0, 9) = 0;
    _hessian(1, 9) = 0;
    _hessian(2, 9) = 0;
    _hessian(3, 9) = 0;
    _hessian(4, 9) = 0;
    _hessian(5, 9) = 0;
    _hessian(6, 9) = 0;
    _hessian(7, 9) = 0;
    _hessian(8, 9) = 0;
    _hessian(9, 9) =
        std::pow(_tmp216, Scalar(2)) * _tmp338 + std::pow(_tmp218, Scalar(2)) * _tmp338;
    _hessian(10, 9) = _tmp216 * _tmp352 + _tmp229 * _tmp368;
    _hessian(11, 9) = _tmp216 * _tmp354 + _tmp218 * _tmp353;
    _hessian(12, 9) = _tmp216 * _tmp355 + _tmp244 * _tmp368;
    _hessian(13, 9) = _tmp249 * _tmp351 + _tmp251 * _tmp368;
    _hessian(14, 9) = _tmp218 * _tmp369 + _tmp257 * _tmp351;
    _hessian(15, 9) = _tmp282 * _tmp351 + _tmp283 * _tmp368;
    _hessian(16, 9) = _tmp218 * _tmp359 + _tmp301 * _tmp351;
    _hessian(17, 9) = _tmp218 * _tmp367 + _tmp318 * _tmp351;
    _hessian(18, 9) = _tmp216 * _tmp361 + _tmp218 * _tmp370;
    _hessian(0, 10) = 0;
    _hessian(1, 10) = 0;
    _hessian(2, 10) = 0;
    _hessian(3, 10) = 0;
    _hessian(4, 10) = 0;
    _hessian(5, 10) = 0;
    _hessian(6, 10) = 0;
    _hessian(7, 10) = 0;
    _hessian(8, 10) = 0;
    _hessian(9, 10) = 0;
    _hessian(10, 10) =
        std::pow(_tmp227, Scalar(2)) * _tmp338 + std::pow(_tmp229, Scalar(2)) * _tmp338;
    _hessian(11, 10) = _tmp229 * _tmp353 + _tmp234 * _tmp352;
    _hessian(12, 10) = _tmp227 * _tmp355 + _tmp229 * _tmp371;
    _hessian(13, 10) = _tmp249 * _tmp352 + _tmp251 * _tmp372;
    _hessian(14, 10) = _tmp229 * _tmp369 + _tmp257 * _tmp352;
    _hessian(15, 10) = _tmp282 * _tmp352 + _tmp283 * _tmp372;
    _hessian(16, 10) = _tmp229 * _tmp359 + _tmp301 * _tmp352;
    _hessian(17, 10) = _tmp229 * _tmp367 + _tmp318 * _tmp352;
    _hessian(18, 10) = _tmp229 * _tmp370 + _tmp335 * _tmp352;
    _hessian(0, 11) = 0;
    _hessian(1, 11) = 0;
    _hessian(2, 11) = 0;
    _hessian(3, 11) = 0;
    _hessian(4, 11) = 0;
    _hessian(5, 11) = 0;
    _hessian(6, 11) = 0;
    _hessian(7, 11) = 0;
    _hessian(8, 11) = 0;
    _hessian(9, 11) = 0;
    _hessian(10, 11) = 0;
    _hessian(11, 11) =
        std::pow(_tmp234, Scalar(2)) * _tmp338 + std::pow(_tmp236, Scalar(2)) * _tmp338;
    _hessian(12, 11) = _tmp234 * _tmp355 + _tmp244 * _tmp353;
    _hessian(13, 11) = _tmp249 * _tmp354 + _tmp251 * _tmp353;
    _hessian(14, 11) = _tmp257 * _tmp354 + _tmp258 * _tmp353;
    _hessian(15, 11) = _tmp282 * _tmp354 + _tmp283 * _tmp353;
    _hessian(16, 11) = _tmp236 * _tmp359 + _tmp301 * _tmp354;
    _hessian(17, 11) = _tmp318 * _tmp354 + _tmp319 * _tmp353;
    _hessian(18, 11) = _tmp335 * _tmp354 + _tmp337 * _tmp353;
    _hessian(0, 12) = 0;
    _hessian(1, 12) = 0;
    _hessian(2, 12) = 0;
    _hessian(3, 12) = 0;
    _hessian(4, 12) = 0;
    _hessian(5, 12) = 0;
    _hessian(6, 12) = 0;
    _hessian(7, 12) = 0;
    _hessian(8, 12) = 0;
    _hessian(9, 12) = 0;
    _hessian(10, 12) = 0;
    _hessian(11, 12) = 0;
    _hessian(12, 12) =
        std::pow(_tmp242, Scalar(2)) * _tmp338 + std::pow(_tmp244, Scalar(2)) * _tmp338;
    _hessian(13, 12) = _tmp249 * _tmp355 + _tmp251 * _tmp371;
    _hessian(14, 12) = _tmp244 * _tmp369 + _tmp257 * _tmp355;
    _hessian(15, 12) = _tmp282 * _tmp355 + _tmp283 * _tmp371;
    _hessian(16, 12) = _tmp244 * _tmp359 + _tmp301 * _tmp355;
    _hessian(17, 12) = _tmp244 * _tmp367 + _tmp318 * _tmp355;
    _hessian(18, 12) = _tmp244 * _tmp370 + _tmp335 * _tmp355;
    _hessian(0, 13) = 0;
    _hessian(1, 13) = 0;
    _hessian(2, 13) = 0;
    _hessian(3, 13) = 0;
    _hessian(4, 13) = 0;
    _hessian(5, 13) = 0;
    _hessian(6, 13) = 0;
    _hessian(7, 13) = 0;
    _hessian(8, 13) = 0;
    _hessian(9, 13) = 0;
    _hessian(10, 13) = 0;
    _hessian(11, 13) = 0;
    _hessian(12, 13) = 0;
    _hessian(13, 13) =
        std::pow(_tmp249, Scalar(2)) * _tmp338 + std::pow(_tmp251, Scalar(2)) * _tmp338;
    _hessian(14, 13) = _tmp251 * _tmp369 + _tmp257 * _tmp356;
    _hessian(15, 13) = _tmp251 * _tmp283 * _tmp338 + _tmp282 * _tmp356;
    _hessian(16, 13) = _tmp251 * _tmp359 + _tmp301 * _tmp356;
    _hessian(17, 13) = _tmp251 * _tmp367 + _tmp318 * _tmp356;
    _hessian(18, 13) = _tmp249 * _tmp361 + _tmp251 * _tmp370;
    _hessian(0, 14) = 0;
    _hessian(1, 14) = 0;
    _hessian(2, 14) = 0;
    _hessian(3, 14) = 0;
    _hessian(4, 14) = 0;
    _hessian(5, 14) = 0;
    _hessian(6, 14) = 0;
    _hessian(7, 14) = 0;
    _hessian(8, 14) = 0;
    _hessian(9, 14) = 0;
    _hessian(10, 14) = 0;
    _hessian(11, 14) = 0;
    _hessian(12, 14) = 0;
    _hessian(13, 14) = 0;
    _hessian(14, 14) =
        std::pow(_tmp257, Scalar(2)) * _tmp338 + std::pow(_tmp258, Scalar(2)) * _tmp338;
    _hessian(15, 14) = _tmp257 * _tmp358 + _tmp283 * _tmp369;
    _hessian(16, 14) = _tmp258 * _tmp359 + _tmp301 * _tmp357;
    _hessian(17, 14) = _tmp258 * _tmp367 + _tmp318 * _tmp357;
    _hessian(18, 14) = _tmp257 * _tmp361 + _tmp337 * _tmp369;
    _hessian(0, 15) = 0;
    _hessian(1, 15) = 0;
    _hessian(2, 15) = 0;
    _hessian(3, 15) = 0;
    _hessian(4, 15) = 0;
    _hessian(5, 15) = 0;
    _hessian(6, 15) = 0;
    _hessian(7, 15) = 0;
    _hessian(8, 15) = 0;
    _hessian(9, 15) = 0;
    _hessian(10, 15) = 0;
    _hessian(11, 15) = 0;
    _hessian(12, 15) = 0;
    _hessian(13, 15) = 0;
    _hessian(14, 15) = 0;
    _hessian(15, 15) =
        std::pow(_tmp282, Scalar(2)) * _tmp338 + std::pow(_tmp283, Scalar(2)) * _tmp338;
    _hessian(16, 15) = _tmp283 * _tmp359 + _tmp301 * _tmp358;
    _hessian(17, 15) = _tmp283 * _tmp367 + _tmp318 * _tmp358;
    _hessian(18, 15) = _tmp282 * _tmp361 + _tmp283 * _tmp370;
    _hessian(0, 16) = 0;
    _hessian(1, 16) = 0;
    _hessian(2, 16) = 0;
    _hessian(3, 16) = 0;
    _hessian(4, 16) = 0;
    _hessian(5, 16) = 0;
    _hessian(6, 16) = 0;
    _hessian(7, 16) = 0;
    _hessian(8, 16) = 0;
    _hessian(9, 16) = 0;
    _hessian(10, 16) = 0;
    _hessian(11, 16) = 0;
    _hessian(12, 16) = 0;
    _hessian(13, 16) = 0;
    _hessian(14, 16) = 0;
    _hessian(15, 16) = 0;
    _hessian(16, 16) =
        std::pow(_tmp301, Scalar(2)) * _tmp338 + std::pow(_tmp303, Scalar(2)) * _tmp338;
    _hessian(17, 16) = _tmp318 * _tmp360 + _tmp319 * _tmp359;
    _hessian(18, 16) = _tmp301 * _tmp361 + _tmp337 * _tmp359;
    _hessian(0, 17) = 0;
    _hessian(1, 17) = 0;
    _hessian(2, 17) = 0;
    _hessian(3, 17) = 0;
    _hessian(4, 17) = 0;
    _hessian(5, 17) = 0;
    _hessian(6, 17) = 0;
    _hessian(7, 17) = 0;
    _hessian(8, 17) = 0;
    _hessian(9, 17) = 0;
    _hessian(10, 17) = 0;
    _hessian(11, 17) = 0;
    _hessian(12, 17) = 0;
    _hessian(13, 17) = 0;
    _hessian(14, 17) = 0;
    _hessian(15, 17) = 0;
    _hessian(16, 17) = 0;
    _hessian(17, 17) =
        std::pow(_tmp318, Scalar(2)) * _tmp338 + std::pow(_tmp319, Scalar(2)) * _tmp338;
    _hessian(18, 17) = _tmp318 * _tmp361 + _tmp337 * _tmp367;
    _hessian(0, 18) = 0;
    _hessian(1, 18) = 0;
    _hessian(2, 18) = 0;
    _hessian(3, 18) = 0;
    _hessian(4, 18) = 0;
    _hessian(5, 18) = 0;
    _hessian(6, 18) = 0;
    _hessian(7, 18) = 0;
    _hessian(8, 18) = 0;
    _hessian(9, 18) = 0;
    _hessian(10, 18) = 0;
    _hessian(11, 18) = 0;
    _hessian(12, 18) = 0;
    _hessian(13, 18) = 0;
    _hessian(14, 18) = 0;
    _hessian(15, 18) = 0;
    _hessian(16, 18) = 0;
    _hessian(17, 18) = 0;
    _hessian(18, 18) =
        std::pow(_tmp335, Scalar(2)) * _tmp338 + std::pow(_tmp337, Scalar(2)) * _tmp338;
  }

  if (rhs != nullptr) {
    Eigen::Matrix<Scalar, 19, 1>& _rhs = (*rhs);

    _rhs(0, 0) = _tmp104 * _tmp120 + _tmp115 * _tmp99;
    _rhs(1, 0) = _tmp103 * _tmp134 + _tmp129 * _tmp99;
    _rhs(2, 0) = _tmp103 * _tmp148 + _tmp143 * _tmp99;
    _rhs(3, 0) = _tmp103 * _tmp167 + _tmp165 * _tmp99;
    _rhs(4, 0) = _tmp104 * _tmp181 + _tmp180 * _tmp99;
    _rhs(5, 0) = _tmp100 * _tmp189 + _tmp104 * _tmp190;
    _rhs(6, 0) = _tmp104 * _tmp194 + _tmp193 * _tmp99;
    _rhs(7, 0) = _tmp103 * _tmp199 + _tmp197 * _tmp99;
    _rhs(8, 0) = _tmp103 * _tmp204 + _tmp202 * _tmp99;
    _rhs(9, 0) = _tmp103 * _tmp219 + _tmp217 * _tmp99;
    _rhs(10, 0) = _tmp103 * _tmp230 + _tmp228 * _tmp99;
    _rhs(11, 0) = _tmp103 * _tmp237 + _tmp235 * _tmp99;
    _rhs(12, 0) = _tmp104 * _tmp244 + _tmp243 * _tmp99;
    _rhs(13, 0) = _tmp103 * _tmp252 + _tmp250 * _tmp99;
    _rhs(14, 0) = _tmp100 * _tmp257 + _tmp104 * _tmp258;
    _rhs(15, 0) = _tmp100 * _tmp282 + _tmp104 * _tmp283;
    _rhs(16, 0) = _tmp104 * _tmp303 + _tmp302 * _tmp99;
    _rhs(17, 0) = _tmp100 * _tmp318 + _tmp103 * _tmp320;
    _rhs(18, 0) = _tmp104 * _tmp337 + _tmp336 * _tmp99;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
