// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: testMatrix1
 *
 * Args:
 *     mat: Matrix15_15
 *
 * Outputs:
 *     res: Matrix15_15
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 15, 15> Testmatrix1(const Eigen::Matrix<Scalar, 15, 15>& mat) {
  // Total ops: 0

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  Eigen::Matrix<Scalar, 15, 15> _res;

  _res(0, 0) = mat(0, 0);
  _res(1, 0) = mat(1, 0);
  _res(2, 0) = mat(2, 0);
  _res(3, 0) = mat(3, 0);
  _res(4, 0) = mat(4, 0);
  _res(5, 0) = mat(5, 0);
  _res(6, 0) = mat(6, 0);
  _res(7, 0) = mat(7, 0);
  _res(8, 0) = mat(8, 0);
  _res(9, 0) = mat(9, 0);
  _res(10, 0) = mat(10, 0);
  _res(11, 0) = mat(11, 0);
  _res(12, 0) = mat(12, 0);
  _res(13, 0) = mat(13, 0);
  _res(14, 0) = mat(14, 0);
  _res(0, 1) = mat(0, 1);
  _res(1, 1) = mat(1, 1);
  _res(2, 1) = mat(2, 1);
  _res(3, 1) = mat(3, 1);
  _res(4, 1) = mat(4, 1);
  _res(5, 1) = mat(5, 1);
  _res(6, 1) = mat(6, 1);
  _res(7, 1) = mat(7, 1);
  _res(8, 1) = mat(8, 1);
  _res(9, 1) = mat(9, 1);
  _res(10, 1) = mat(10, 1);
  _res(11, 1) = mat(11, 1);
  _res(12, 1) = mat(12, 1);
  _res(13, 1) = mat(13, 1);
  _res(14, 1) = mat(14, 1);
  _res(0, 2) = mat(0, 2);
  _res(1, 2) = mat(1, 2);
  _res(2, 2) = mat(2, 2);
  _res(3, 2) = mat(3, 2);
  _res(4, 2) = mat(4, 2);
  _res(5, 2) = mat(5, 2);
  _res(6, 2) = mat(6, 2);
  _res(7, 2) = mat(7, 2);
  _res(8, 2) = mat(8, 2);
  _res(9, 2) = mat(9, 2);
  _res(10, 2) = mat(10, 2);
  _res(11, 2) = mat(11, 2);
  _res(12, 2) = mat(12, 2);
  _res(13, 2) = mat(13, 2);
  _res(14, 2) = mat(14, 2);
  _res(0, 3) = mat(0, 3);
  _res(1, 3) = mat(1, 3);
  _res(2, 3) = mat(2, 3);
  _res(3, 3) = mat(3, 3);
  _res(4, 3) = mat(4, 3);
  _res(5, 3) = mat(5, 3);
  _res(6, 3) = mat(6, 3);
  _res(7, 3) = mat(7, 3);
  _res(8, 3) = mat(8, 3);
  _res(9, 3) = mat(9, 3);
  _res(10, 3) = mat(10, 3);
  _res(11, 3) = mat(11, 3);
  _res(12, 3) = mat(12, 3);
  _res(13, 3) = mat(13, 3);
  _res(14, 3) = mat(14, 3);
  _res(0, 4) = mat(0, 4);
  _res(1, 4) = mat(1, 4);
  _res(2, 4) = mat(2, 4);
  _res(3, 4) = mat(3, 4);
  _res(4, 4) = mat(4, 4);
  _res(5, 4) = mat(5, 4);
  _res(6, 4) = mat(6, 4);
  _res(7, 4) = mat(7, 4);
  _res(8, 4) = mat(8, 4);
  _res(9, 4) = mat(9, 4);
  _res(10, 4) = mat(10, 4);
  _res(11, 4) = mat(11, 4);
  _res(12, 4) = mat(12, 4);
  _res(13, 4) = mat(13, 4);
  _res(14, 4) = mat(14, 4);
  _res(0, 5) = mat(0, 5);
  _res(1, 5) = mat(1, 5);
  _res(2, 5) = mat(2, 5);
  _res(3, 5) = mat(3, 5);
  _res(4, 5) = mat(4, 5);
  _res(5, 5) = mat(5, 5);
  _res(6, 5) = mat(6, 5);
  _res(7, 5) = mat(7, 5);
  _res(8, 5) = mat(8, 5);
  _res(9, 5) = mat(9, 5);
  _res(10, 5) = mat(10, 5);
  _res(11, 5) = mat(11, 5);
  _res(12, 5) = mat(12, 5);
  _res(13, 5) = mat(13, 5);
  _res(14, 5) = mat(14, 5);
  _res(0, 6) = mat(0, 6);
  _res(1, 6) = mat(1, 6);
  _res(2, 6) = mat(2, 6);
  _res(3, 6) = mat(3, 6);
  _res(4, 6) = mat(4, 6);
  _res(5, 6) = mat(5, 6);
  _res(6, 6) = mat(6, 6);
  _res(7, 6) = mat(7, 6);
  _res(8, 6) = mat(8, 6);
  _res(9, 6) = mat(9, 6);
  _res(10, 6) = mat(10, 6);
  _res(11, 6) = mat(11, 6);
  _res(12, 6) = mat(12, 6);
  _res(13, 6) = mat(13, 6);
  _res(14, 6) = mat(14, 6);
  _res(0, 7) = mat(0, 7);
  _res(1, 7) = mat(1, 7);
  _res(2, 7) = mat(2, 7);
  _res(3, 7) = mat(3, 7);
  _res(4, 7) = mat(4, 7);
  _res(5, 7) = mat(5, 7);
  _res(6, 7) = mat(6, 7);
  _res(7, 7) = mat(7, 7);
  _res(8, 7) = mat(8, 7);
  _res(9, 7) = mat(9, 7);
  _res(10, 7) = mat(10, 7);
  _res(11, 7) = mat(11, 7);
  _res(12, 7) = mat(12, 7);
  _res(13, 7) = mat(13, 7);
  _res(14, 7) = mat(14, 7);
  _res(0, 8) = mat(0, 8);
  _res(1, 8) = mat(1, 8);
  _res(2, 8) = mat(2, 8);
  _res(3, 8) = mat(3, 8);
  _res(4, 8) = mat(4, 8);
  _res(5, 8) = mat(5, 8);
  _res(6, 8) = mat(6, 8);
  _res(7, 8) = mat(7, 8);
  _res(8, 8) = mat(8, 8);
  _res(9, 8) = mat(9, 8);
  _res(10, 8) = mat(10, 8);
  _res(11, 8) = mat(11, 8);
  _res(12, 8) = mat(12, 8);
  _res(13, 8) = mat(13, 8);
  _res(14, 8) = mat(14, 8);
  _res(0, 9) = mat(0, 9);
  _res(1, 9) = mat(1, 9);
  _res(2, 9) = mat(2, 9);
  _res(3, 9) = mat(3, 9);
  _res(4, 9) = mat(4, 9);
  _res(5, 9) = mat(5, 9);
  _res(6, 9) = mat(6, 9);
  _res(7, 9) = mat(7, 9);
  _res(8, 9) = mat(8, 9);
  _res(9, 9) = mat(9, 9);
  _res(10, 9) = mat(10, 9);
  _res(11, 9) = mat(11, 9);
  _res(12, 9) = mat(12, 9);
  _res(13, 9) = mat(13, 9);
  _res(14, 9) = mat(14, 9);
  _res(0, 10) = mat(0, 10);
  _res(1, 10) = mat(1, 10);
  _res(2, 10) = mat(2, 10);
  _res(3, 10) = mat(3, 10);
  _res(4, 10) = mat(4, 10);
  _res(5, 10) = mat(5, 10);
  _res(6, 10) = mat(6, 10);
  _res(7, 10) = mat(7, 10);
  _res(8, 10) = mat(8, 10);
  _res(9, 10) = mat(9, 10);
  _res(10, 10) = mat(10, 10);
  _res(11, 10) = mat(11, 10);
  _res(12, 10) = mat(12, 10);
  _res(13, 10) = mat(13, 10);
  _res(14, 10) = mat(14, 10);
  _res(0, 11) = mat(0, 11);
  _res(1, 11) = mat(1, 11);
  _res(2, 11) = mat(2, 11);
  _res(3, 11) = mat(3, 11);
  _res(4, 11) = mat(4, 11);
  _res(5, 11) = mat(5, 11);
  _res(6, 11) = mat(6, 11);
  _res(7, 11) = mat(7, 11);
  _res(8, 11) = mat(8, 11);
  _res(9, 11) = mat(9, 11);
  _res(10, 11) = mat(10, 11);
  _res(11, 11) = mat(11, 11);
  _res(12, 11) = mat(12, 11);
  _res(13, 11) = mat(13, 11);
  _res(14, 11) = mat(14, 11);
  _res(0, 12) = mat(0, 12);
  _res(1, 12) = mat(1, 12);
  _res(2, 12) = mat(2, 12);
  _res(3, 12) = mat(3, 12);
  _res(4, 12) = mat(4, 12);
  _res(5, 12) = mat(5, 12);
  _res(6, 12) = mat(6, 12);
  _res(7, 12) = mat(7, 12);
  _res(8, 12) = mat(8, 12);
  _res(9, 12) = mat(9, 12);
  _res(10, 12) = mat(10, 12);
  _res(11, 12) = mat(11, 12);
  _res(12, 12) = mat(12, 12);
  _res(13, 12) = mat(13, 12);
  _res(14, 12) = mat(14, 12);
  _res(0, 13) = mat(0, 13);
  _res(1, 13) = mat(1, 13);
  _res(2, 13) = mat(2, 13);
  _res(3, 13) = mat(3, 13);
  _res(4, 13) = mat(4, 13);
  _res(5, 13) = mat(5, 13);
  _res(6, 13) = mat(6, 13);
  _res(7, 13) = mat(7, 13);
  _res(8, 13) = mat(8, 13);
  _res(9, 13) = mat(9, 13);
  _res(10, 13) = mat(10, 13);
  _res(11, 13) = mat(11, 13);
  _res(12, 13) = mat(12, 13);
  _res(13, 13) = mat(13, 13);
  _res(14, 13) = mat(14, 13);
  _res(0, 14) = mat(0, 14);
  _res(1, 14) = mat(1, 14);
  _res(2, 14) = mat(2, 14);
  _res(3, 14) = mat(3, 14);
  _res(4, 14) = mat(4, 14);
  _res(5, 14) = mat(5, 14);
  _res(6, 14) = mat(6, 14);
  _res(7, 14) = mat(7, 14);
  _res(8, 14) = mat(8, 14);
  _res(9, 14) = mat(9, 14);
  _res(10, 14) = mat(10, 14);
  _res(11, 14) = mat(11, 14);
  _res(12, 14) = mat(12, 14);
  _res(13, 14) = mat(13, 14);
  _res(14, 14) = mat(14, 14);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
